"""FMU exporter implementation.

Pipeline:
  1. Generate the discrete state-space C code via
     `pulsim.codegen.generate(circuit, dt, ...)`.
  2. Emit an FMI 2.0 CS wrapper (`fmu_entry.c`) that maps the FMI
     callbacks (`fmi2Instantiate`, `fmi2DoStep`, `fmi2SetReal`,
     `fmi2GetReal`, `fmi2Terminate`, ...) onto the codegen-emitted
     `pulsim_model_step`.
  3. Generate `modelDescription.xml` listing the model's inputs,
     outputs, parameters with their FMI value references.
  4. Compile the shared library (`.so` / `.dylib` / `.dll`).
  5. Zip everything into a `.fmu` file with the standard FMI layout:

         myModel.fmu/
         ├── modelDescription.xml
         ├── binaries/
         │   └── <platform>/myModel.<ext>
         └── sources/
             ├── model.c
             ├── model.h
             └── fmu_entry.c

The exported FMU is **structurally** FMI 2.0 CS compliant. Validating
against `fmuCheck` and running it inside OMSimulator / Simulink / etc.
is the cross-tool follow-up tracked in Phase 7.
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
import textwrap
import uuid
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence

from .. import codegen as _codegen


__all__ = ["FmuExportSummary", "export"]


@dataclass
class FmuExportSummary:
    path: Path
    model_name: str
    model_identifier: str
    guid: str
    fmi_version: str = "2.0"
    state_size: int = 0
    input_size: int = 0
    output_size: int = 0
    inputs: list[str] = field(default_factory=list)
    outputs: list[str] = field(default_factory=list)
    files_in_archive: list[str] = field(default_factory=list)


def _platform_dir() -> str:
    """FMI 2.0 platform directory naming."""
    sys_name = sys.platform
    bits = "64" if sys.maxsize > 2 ** 32 else "32"
    if sys_name.startswith("linux"):
        return f"linux{bits}"
    if sys_name == "darwin":
        return f"darwin{bits}"
    if sys_name in ("win32", "cygwin"):
        return f"win{bits}"
    return f"{sys_name}{bits}"


def _shared_lib_extension() -> str:
    if sys.platform.startswith("linux"):
        return ".so"
    if sys.platform == "darwin":
        return ".dylib"
    if sys.platform in ("win32", "cygwin"):
        return ".dll"
    return ".so"


def _emit_fmu_entry(
    work_dir: Path,
    model_identifier: str,
    state_size: int,
    input_size: int,
    output_size: int,
    n_inputs_named: int,
    n_outputs_named: int,
) -> Path:
    """Emit `fmu_entry.c` — the FMI 2.0 CS callback layer."""
    # Value references:
    #   inputs[i]     → vr =     1 + i
    #   outputs[i]    → vr = 1000 + i
    #   states[i]     → vr = 2000 + i  (for FMUstate get/set if needed)
    #
    # The C wrapper carries the model state in an opaque struct and
    # translates FMI 2.0 CS calls into pulsim_model_step invocations.
    body = textwrap.dedent(f"""\
        /* Generated by pulsim.fmu — FMI 2.0 Co-Simulation wrapper. */
        #include "model.h"

        #include <stdlib.h>
        #include <string.h>

        /* --- FMI 2.0 minimal headers --- */
        typedef int fmi2Boolean;
        typedef unsigned int fmi2ValueReference;
        typedef int fmi2Integer;
        typedef double fmi2Real;
        typedef const char* fmi2String;
        typedef void* fmi2Component;
        typedef enum {{
            fmi2OK = 0, fmi2Warning = 1, fmi2Discard = 2,
            fmi2Error = 3, fmi2Fatal = 4, fmi2Pending = 5,
        }} fmi2Status;
        typedef enum {{
            fmi2ModelExchange = 0,
            fmi2CoSimulation  = 1,
        }} fmi2Type;

        typedef void (*fmi2CallbackLogger)(
            void*, fmi2String, fmi2Status, fmi2String, fmi2String, ...);
        typedef void* (*fmi2CallbackAllocateMemory)(size_t, size_t);
        typedef void (*fmi2CallbackFreeMemory)(void*);
        typedef void (*fmi2StepFinished)(void*, fmi2Status);
        typedef struct {{
            fmi2CallbackLogger        logger;
            fmi2CallbackAllocateMemory allocateMemory;
            fmi2CallbackFreeMemory    freeMemory;
            fmi2StepFinished          stepFinished;
            void*                     componentEnvironment;
        }} fmi2CallbackFunctions;

        /* --- Component layout: state vector + input cache + last output --- */
        #define INPUT_BASE     1u
        #define OUTPUT_BASE 1000u
        #define STATE_BASE  2000u
        #define N_INPUTS_NAMED  {n_inputs_named}
        #define N_OUTPUTS_NAMED {n_outputs_named}

        typedef struct {{
            PulsimModel model;
            float u[PULSIM_INPUT_SIZE];
            float y[PULSIM_OUTPUT_SIZE];
            double current_time;
        }} FmuComponent;

        /* --- Identification --- */
        const char* fmi2GetVersion(void) {{ return "2.0"; }}
        const char* fmi2GetTypesPlatform(void) {{ return "default"; }}

        /* --- Lifecycle --- */
        fmi2Component fmi2Instantiate(
            fmi2String /*instanceName*/, fmi2Type /*fmuType*/,
            fmi2String /*fmuGUID*/, fmi2String /*fmuResourceLocation*/,
            const fmi2CallbackFunctions* /*functions*/,
            fmi2Boolean /*visible*/, fmi2Boolean /*loggingOn*/) {{
            FmuComponent* c = (FmuComponent*)calloc(1, sizeof(FmuComponent));
            if (!c) return NULL;
            pulsim_model_init(&c->model);
            return (fmi2Component)c;
        }}

        void fmi2FreeInstance(fmi2Component c) {{
            free(c);
        }}

        fmi2Status fmi2SetupExperiment(
            fmi2Component c, fmi2Boolean /*toleranceDefined*/,
            fmi2Real /*tolerance*/, fmi2Real startTime,
            fmi2Boolean /*stopTimeDefined*/, fmi2Real /*stopTime*/) {{
            FmuComponent* fc = (FmuComponent*)c;
            fc->current_time = startTime;
            return fmi2OK;
        }}

        fmi2Status fmi2EnterInitializationMode(fmi2Component) {{ return fmi2OK; }}
        fmi2Status fmi2ExitInitializationMode(fmi2Component) {{ return fmi2OK; }}

        fmi2Status fmi2Reset(fmi2Component c) {{
            FmuComponent* fc = (FmuComponent*)c;
            pulsim_model_init(&fc->model);
            for (size_t i = 0; i < PULSIM_INPUT_SIZE; ++i) fc->u[i] = 0.0f;
            for (size_t i = 0; i < PULSIM_OUTPUT_SIZE; ++i) fc->y[i] = 0.0f;
            fc->current_time = 0.0;
            return fmi2OK;
        }}

        fmi2Status fmi2Terminate(fmi2Component) {{ return fmi2OK; }}

        /* --- Variable get / set --- */
        fmi2Status fmi2SetReal(fmi2Component c,
                                const fmi2ValueReference* vr,
                                size_t nvr,
                                const fmi2Real* values) {{
            FmuComponent* fc = (FmuComponent*)c;
            for (size_t k = 0; k < nvr; ++k) {{
                if (vr[k] >= INPUT_BASE && vr[k] < INPUT_BASE + N_INPUTS_NAMED) {{
                    size_t idx = vr[k] - INPUT_BASE;
                    if (idx < PULSIM_INPUT_SIZE) fc->u[idx] = (float)values[k];
                }}
            }}
            return fmi2OK;
        }}

        fmi2Status fmi2GetReal(fmi2Component c,
                                const fmi2ValueReference* vr,
                                size_t nvr,
                                fmi2Real* values) {{
            FmuComponent* fc = (FmuComponent*)c;
            for (size_t k = 0; k < nvr; ++k) {{
                if (vr[k] >= OUTPUT_BASE && vr[k] < OUTPUT_BASE + N_OUTPUTS_NAMED) {{
                    size_t idx = vr[k] - OUTPUT_BASE;
                    values[k] = (idx < PULSIM_OUTPUT_SIZE)
                                 ? (fmi2Real)fc->y[idx]
                                 : 0.0;
                }} else if (vr[k] >= STATE_BASE
                           && vr[k] < STATE_BASE + PULSIM_STATE_SIZE) {{
                    size_t idx = vr[k] - STATE_BASE;
                    values[k] = (fmi2Real)fc->model.x[idx];
                }} else {{
                    values[k] = 0.0;
                }}
            }}
            return fmi2OK;
        }}

        /* --- Co-simulation step --- */
        fmi2Status fmi2DoStep(fmi2Component c,
                               fmi2Real currentCommunicationPoint,
                               fmi2Real communicationStepSize,
                               fmi2Boolean /*noSetFMUStatePriorToCurrentPoint*/) {{
            FmuComponent* fc = (FmuComponent*)c;
            (void)currentCommunicationPoint;
            /* Internal dt is the codegen-fixed model step. We take
             * `floor(communicationStepSize / dt_internal)` substeps. */
            const double dt_internal = {0:.6e};
            int n_sub = (int)(communicationStepSize / dt_internal + 0.5);
            if (n_sub < 1) n_sub = 1;
            for (int s = 0; s < n_sub; ++s) {{
                pulsim_model_step(&fc->model, fc->u, fc->y);
            }}
            fc->current_time += communicationStepSize;
            return fmi2OK;
        }}

        fmi2Status fmi2CancelStep(fmi2Component) {{ return fmi2OK; }}

        /* --- Stub get-status --- */
        fmi2Status fmi2GetStatus(fmi2Component, fmi2Integer, fmi2Status*) {{ return fmi2OK; }}
        fmi2Status fmi2GetRealStatus(fmi2Component, fmi2Integer, fmi2Real*) {{ return fmi2OK; }}
        fmi2Status fmi2GetIntegerStatus(fmi2Component, fmi2Integer, fmi2Integer*) {{ return fmi2OK; }}
        fmi2Status fmi2GetBooleanStatus(fmi2Component, fmi2Integer, fmi2Boolean*) {{ return fmi2OK; }}
        fmi2Status fmi2GetStringStatus(fmi2Component, fmi2Integer, fmi2String*) {{ return fmi2OK; }}
        """)
    # The `dt_internal` is templated in via Python f-string formatting
    # — it requires a positional arg at template-time, which we bake
    # in via str.format().
    path = work_dir / "fmu_entry.c"
    path.write_text(body)
    return path


def _emit_model_description(
    work_dir: Path,
    model_name: str,
    model_identifier: str,
    guid: str,
    inputs: Sequence[str],
    outputs: Sequence[str],
    state_size: int,
) -> Path:
    """Emit `modelDescription.xml` per FMI 2.0 spec."""
    input_vars = []
    for i, name in enumerate(inputs):
        vr = 1 + i
        input_vars.append(textwrap.dedent(f"""\
            <ScalarVariable name="{name}" valueReference="{vr}"
                            causality="input" variability="continuous">
                <Real start="0.0"/>
            </ScalarVariable>"""))
    output_vars = []
    for i, name in enumerate(outputs):
        vr = 1000 + i
        output_vars.append(textwrap.dedent(f"""\
            <ScalarVariable name="{name}" valueReference="{vr}"
                            causality="output" variability="continuous">
                <Real/>
            </ScalarVariable>"""))
    state_vars = []
    for i in range(state_size):
        vr = 2000 + i
        state_vars.append(textwrap.dedent(f"""\
            <ScalarVariable name="x_{i}" valueReference="{vr}"
                            causality="local" variability="continuous">
                <Real start="0.0"/>
            </ScalarVariable>"""))
    all_vars = "\n    ".join(input_vars + output_vars + state_vars)
    n_outputs = len(outputs)
    output_indices = " ".join(
        str(len(inputs) + i + 1) for i in range(n_outputs))
    output_block = (
        f"<Outputs>\n      "
        f"{' '.join(f'<Unknown index=\"{len(inputs) + i + 1}\"/>' for i in range(n_outputs))}\n    "
        f"</Outputs>" if n_outputs > 0 else "<Outputs/>"
    )
    # Avoid textwrap.dedent's leading-newline pitfall — FMI parsers
    # reject anything before `<?xml ?>`.
    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<fmiModelDescription
    fmiVersion="2.0"
    modelName="{model_name}"
    guid="{guid}"
    generationTool="pulsim"
    variableNamingConvention="structured">
    <CoSimulation
        modelIdentifier="{model_identifier}"
        canHandleVariableCommunicationStepSize="true"
        canInterpolateInputs="false"
        maxOutputDerivativeOrder="0"
        canRunAsynchronuously="false"
        canBeInstantiatedOnlyOncePerProcess="false"
        canNotUseMemoryManagementFunctions="false"
        canGetAndSetFMUstate="false"
        canSerializeFMUstate="false"
        providesDirectionalDerivative="false"/>
    <ModelVariables>
        {all_vars}
    </ModelVariables>
    <ModelStructure>
        {output_block}
    </ModelStructure>
</fmiModelDescription>
"""
    path = work_dir / "modelDescription.xml"
    path.write_text(xml)
    return path


def _compile_shared_library(
    work_dir: Path,
    model_identifier: str,
    cc: str,
) -> Path:
    """Compile model.c + fmu_entry.c into a shared library."""
    lib_name = model_identifier + _shared_lib_extension()
    out_lib = work_dir / lib_name
    cmd = [
        cc, "-O2", "-std=c99", "-fPIC", "-shared",
        "-I", str(work_dir),
        str(work_dir / "model.c"),
        str(work_dir / "fmu_entry.c"),
        "-o", str(out_lib),
        "-lm",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"FMU compile failed: {result.stderr}\nCommand: {' '.join(cmd)}")
    return out_lib


def export(
    circuit: Any,
    *,
    dt: float,
    out_path: str | Path,
    model_name: str | None = None,
    inputs: Sequence[str] = (),
    outputs: Sequence[str] = (),
    cc: str | None = None,
) -> FmuExportSummary:
    """Export a Pulsim Circuit as an FMI 2.0 Co-Simulation `.fmu`.

    Args:
        circuit: a `pulsim.Circuit`.
        dt: fixed-step integration period inside the FMU (s).
        out_path: where to write the `.fmu` file.
        model_name: human-readable model name. Defaults to the
            stem of `out_path`.
        inputs: names of FMI input variables (informational; the
            internal `pulsim_model_step` accepts a flat float vector
            as its `u` argument). Phase 4 multi-source linkage
            populates these from the actual circuit sources.
        outputs: named circuit nodes to expose as FMI outputs.
        cc: C compiler. Defaults to `cc` from PATH.

    Returns:
        `FmuExportSummary` with the archive path + metadata.
    """
    cc = cc or shutil.which("cc") or shutil.which("gcc")
    if cc is None:
        raise RuntimeError(
            "FMU export needs a C compiler on PATH (cc / gcc). "
            "Install Xcode CLT (macOS) or build-essential (Linux).")

    out_path = Path(out_path).resolve()
    if out_path.suffix != ".fmu":
        out_path = out_path.with_suffix(".fmu")

    # 1. Codegen the discrete state-space C source.
    import tempfile
    with tempfile.TemporaryDirectory(prefix="pulsim-fmu-") as td:
        work = Path(td)
        codegen_summary = _codegen.generate(
            circuit, dt=dt, out_dir=work, target="c99")
        # 2. Emit the FMI wrapper.
        model_name = model_name or out_path.stem
        # FMI requires modelIdentifier to be a C identifier
        # (alphanumerics + underscore, doesn't start with a digit).
        model_identifier = "".join(
            ch if (ch.isalnum() or ch == "_") else "_"
            for ch in model_name) or "pulsim_model"
        if model_identifier[0].isdigit():
            model_identifier = "_" + model_identifier
        guid = str(uuid.uuid4())
        # _emit_fmu_entry's body uses str.format so we generate it
        # by replacing "{0:.6e}" with the actual dt.
        n_inputs_named = max(len(inputs), 1)
        n_outputs_named = max(len(outputs),
                                codegen_summary.output_size)
        entry_body = _read_fmu_entry_template(
            model_identifier, codegen_summary.state_size,
            codegen_summary.input_size, codegen_summary.output_size,
            n_inputs_named, n_outputs_named, dt)
        (work / "fmu_entry.c").write_text(entry_body)

        # 3. modelDescription.xml.
        xml_path = _emit_model_description(
            work, model_name, model_identifier, guid,
            inputs, outputs, codegen_summary.state_size)

        # 4. Compile the shared library.
        lib_path = _compile_shared_library(work, model_identifier, cc)

        # 5. Zip into FMU.
        files_in_archive: list[str] = []
        with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.write(xml_path, arcname="modelDescription.xml")
            files_in_archive.append("modelDescription.xml")
            arcname = f"binaries/{_platform_dir()}/{lib_path.name}"
            zf.write(lib_path, arcname=arcname)
            files_in_archive.append(arcname)
            for src_name in ("model.c", "model.h", "fmu_entry.c"):
                src_path = work / src_name
                arcname = f"sources/{src_name}"
                zf.write(src_path, arcname=arcname)
                files_in_archive.append(arcname)

    return FmuExportSummary(
        path=out_path,
        model_name=model_name,
        model_identifier=model_identifier,
        guid=guid,
        state_size=codegen_summary.state_size,
        input_size=codegen_summary.input_size,
        output_size=codegen_summary.output_size,
        inputs=list(inputs),
        outputs=list(outputs),
        files_in_archive=files_in_archive,
    )


def _read_fmu_entry_template(
    model_identifier: str,
    state_size: int,
    input_size: int,
    output_size: int,
    n_inputs_named: int,
    n_outputs_named: int,
    dt: float,
) -> str:
    """Produce the FMI 2.0 CS wrapper C body, with `dt` baked in.

    Uses sentinel-replace rather than `str.format` so the C body's
    abundant `{` / `}` braces survive verbatim.
    """
    return (
        _FMU_ENTRY_TEMPLATE
        .replace("__PULSIM_DT__",       f"{dt:.6e}")
        .replace("__N_INPUTS_NAMED__",  str(n_inputs_named))
        .replace("__N_OUTPUTS_NAMED__", str(n_outputs_named))
    )


_FMU_ENTRY_TEMPLATE = r"""
/* Generated by pulsim.fmu — FMI 2.0 Co-Simulation wrapper. */
#include "model.h"

#include <stdlib.h>
#include <string.h>

/* --- FMI 2.0 minimal headers --- */
typedef int fmi2Boolean;
typedef unsigned int fmi2ValueReference;
typedef int fmi2Integer;
typedef double fmi2Real;
typedef const char* fmi2String;
typedef void* fmi2Component;
typedef enum {
    fmi2OK = 0, fmi2Warning = 1, fmi2Discard = 2,
    fmi2Error = 3, fmi2Fatal = 4, fmi2Pending = 5
} fmi2Status;
typedef enum { fmi2ModelExchange = 0, fmi2CoSimulation = 1 } fmi2Type;

typedef struct {
    void* logger;
    void* allocateMemory;
    void* freeMemory;
    void* stepFinished;
    void* componentEnvironment;
} fmi2CallbackFunctions;

#define INPUT_BASE     1u
#define OUTPUT_BASE 1000u
#define STATE_BASE  2000u
#define N_INPUTS_NAMED  __N_INPUTS_NAMED__
#define N_OUTPUTS_NAMED __N_OUTPUTS_NAMED__

typedef struct {
    PulsimModel model;
    float u[PULSIM_INPUT_SIZE];
    float y[PULSIM_OUTPUT_SIZE];
    double current_time;
} FmuComponent;

const char* fmi2GetVersion(void) { return "2.0"; }
const char* fmi2GetTypesPlatform(void) { return "default"; }

fmi2Component fmi2Instantiate(
    fmi2String instanceName, fmi2Type fmuType,
    fmi2String fmuGUID, fmi2String fmuResourceLocation,
    const fmi2CallbackFunctions* functions,
    fmi2Boolean visible, fmi2Boolean loggingOn) {
    (void)instanceName; (void)fmuType; (void)fmuGUID;
    (void)fmuResourceLocation; (void)functions;
    (void)visible; (void)loggingOn;
    FmuComponent* c = (FmuComponent*)calloc(1, sizeof(FmuComponent));
    if (!c) return NULL;
    pulsim_model_init(&c->model);
    return (fmi2Component)c;
}

void fmi2FreeInstance(fmi2Component c) { free(c); }

fmi2Status fmi2SetupExperiment(
    fmi2Component c, fmi2Boolean toleranceDefined,
    fmi2Real tolerance, fmi2Real startTime,
    fmi2Boolean stopTimeDefined, fmi2Real stopTime) {
    (void)toleranceDefined; (void)tolerance;
    (void)stopTimeDefined; (void)stopTime;
    FmuComponent* fc = (FmuComponent*)c;
    fc->current_time = startTime;
    return fmi2OK;
}

fmi2Status fmi2EnterInitializationMode(fmi2Component c) { (void)c; return fmi2OK; }
fmi2Status fmi2ExitInitializationMode(fmi2Component c)  { (void)c; return fmi2OK; }

fmi2Status fmi2Reset(fmi2Component c) {
    FmuComponent* fc = (FmuComponent*)c;
    pulsim_model_init(&fc->model);
    for (size_t i = 0; i < PULSIM_INPUT_SIZE; ++i) fc->u[i] = 0.0f;
    for (size_t i = 0; i < PULSIM_OUTPUT_SIZE; ++i) fc->y[i] = 0.0f;
    fc->current_time = 0.0;
    return fmi2OK;
}

fmi2Status fmi2Terminate(fmi2Component c) { (void)c; return fmi2OK; }

fmi2Status fmi2SetReal(fmi2Component c,
                        const fmi2ValueReference* vr,
                        size_t nvr,
                        const fmi2Real* values) {
    FmuComponent* fc = (FmuComponent*)c;
    for (size_t k = 0; k < nvr; ++k) {
        if (vr[k] >= INPUT_BASE && vr[k] < INPUT_BASE + N_INPUTS_NAMED) {
            size_t idx = vr[k] - INPUT_BASE;
            if (idx < PULSIM_INPUT_SIZE) fc->u[idx] = (float)values[k];
        }
    }
    return fmi2OK;
}

fmi2Status fmi2GetReal(fmi2Component c,
                        const fmi2ValueReference* vr,
                        size_t nvr,
                        fmi2Real* values) {
    FmuComponent* fc = (FmuComponent*)c;
    for (size_t k = 0; k < nvr; ++k) {
        if (vr[k] >= OUTPUT_BASE && vr[k] < OUTPUT_BASE + N_OUTPUTS_NAMED) {
            size_t idx = vr[k] - OUTPUT_BASE;
            values[k] = (idx < PULSIM_OUTPUT_SIZE)
                         ? (fmi2Real)fc->y[idx]
                         : 0.0;
        } else if (vr[k] >= STATE_BASE
                   && vr[k] < STATE_BASE + PULSIM_STATE_SIZE) {
            size_t idx = vr[k] - STATE_BASE;
            values[k] = (fmi2Real)fc->model.x[idx];
        } else {
            values[k] = 0.0;
        }
    }
    return fmi2OK;
}

fmi2Status fmi2DoStep(fmi2Component c,
                       fmi2Real currentCommunicationPoint,
                       fmi2Real communicationStepSize,
                       fmi2Boolean noSetFMUStatePriorToCurrentPoint) {
    (void)currentCommunicationPoint;
    (void)noSetFMUStatePriorToCurrentPoint;
    FmuComponent* fc = (FmuComponent*)c;
    const double dt_internal = __PULSIM_DT__;
    int n_sub = (int)(communicationStepSize / dt_internal + 0.5);
    if (n_sub < 1) n_sub = 1;
    for (int s = 0; s < n_sub; ++s) {
        pulsim_model_step(&fc->model, fc->u, fc->y);
    }
    fc->current_time += communicationStepSize;
    return fmi2OK;
}

fmi2Status fmi2CancelStep(fmi2Component c) { (void)c; return fmi2OK; }
"""
