"""Custom-code block ("C block") — a PSIM-style sampled subsystem.

A C block reads a user-chosen set of circuit signals (its *inputs*), runs
user code at a user-chosen sample time, and drives a user-chosen set of
signals back into the circuit (its *outputs*), held zero-order between
block steps.

The step code may be a **Python** callable, a **compiled C/C++ shared
library** (loaded via ``ctypes``; C++ via ``extern "C"``), or **inline
C/C++ source** (auto-compiled to a cached shared library). All run on
the fixed-step (**PWL**) engine: the block rides Pulsim's existing
per-step hooks — a throttled ``step_observer`` reads inputs + runs the
user code, and a ``b_extra_fn`` injects the held outputs into controlled
sources — so no kernel change is required. The YAML and GUI surfaces
land in later phases.

Wires
-----
Inputs (read from the circuit):
  * ``("v", node)``    — voltage at ``node``
  * ``("i", branch)``  — current through ``branch`` (inductor or source)

Outputs (drive the circuit), each creates one controlled source:
  * ``("v", n_pos, n_neg)`` — controlled **voltage** source
  * ``("i", n_pos, n_neg)`` — controlled **current** source

Usage
-----
::

    b = p.CircuitBuilder()
    # ... build the power stage ...
    def step(t, dt, inp, out, state):
        out[0] = 0.5 * inp[0]          # your control law
    p.add_c_block(b,
                  inputs=[("v", "vout")],
                  outputs=[("v", "ctrl", "gnd")],
                  dt=1e-4, fn=step)
    res = p.simulate(b, t_end=..., dt=2e-6)   # block runs automatically
"""
from __future__ import annotations

import ctypes
import hashlib
import os
import shutil
import subprocess
import tempfile
import warnings
import weakref
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Optional, Sequence

import numpy as np

__all__ = ["CBlockHandle", "add_c_block", "wire_c_blocks_from_yaml",
           "CBLOCK_ABI"]

_YAML_FIELDS = {"name", "lang", "code", "lib", "symbol", "include_dirs",
                "extra_compile_args", "extra_link_args"}

# Public C ABI a block's compiled code must export (C and C++ via
# ``extern "C"``). ``in``/``out`` are length ``n_in``/``n_out`` double
# buffers; ``state`` is an opaque per-block pointer the block owns
# (allocate in ``pulsim_cblock_init``, free in ``pulsim_cblock_term``,
# or lazily via ``*state``).
CBLOCK_ABI = r"""
void  pulsim_cblock_step(const double* in, int n_in,
                         double* out, int n_out,
                         double t, double dt, void** state);
void* pulsim_cblock_init(int n_in, int n_out);   /* optional */
void  pulsim_cblock_term(void* state);           /* optional */
""".strip()

_C_TEMPLATE = """/* auto-generated by pulsim.add_c_block — do not edit */
#include <math.h>
#include <string.h>
#include <stdlib.h>
void {symbol}(const double* in, int n_in, double* out, int n_out,
              double t, double dt, void** state) {{
    (void)n_in; (void)n_out; (void)t; (void)dt; (void)state;
{body}
}}
"""

_CPP_TEMPLATE = """// auto-generated by pulsim.add_c_block — do not edit
#include <cmath>
#include <cstring>
#include <cstdlib>
extern "C" void {symbol}(const double* in, int n_in, double* out, int n_out,
                         double t, double dt, void** state) {{
    (void)n_in; (void)n_out; (void)t; (void)dt; (void)state;
{body}
}}
"""

# Sign of the b_extra injection into a source's augmented row, i.e. how
# the per-step setpoint maps to the imposed voltage/current. The kernel's
# source-row convention negates the RHS. Validated against the kernel by
# tests/test_c_block.py.
_V_SRC_SIGN = -1.0
_I_SRC_SIGN = -1.0

_V_KINDS = ("v", "V", "node", "voltage")
_I_KINDS = ("i", "I", "current")


@dataclass
class CBlockHandle:
    """Live handle for an added C block (returned by :func:`add_c_block`).

    ``outputs`` and ``state`` are updated in place each block step, so the
    caller can read them between / after simulation for diagnostics.
    """
    name: str
    n_in: int
    n_out: int
    dt_block: float
    state: dict
    inputs: np.ndarray            # last sampled inputs
    outputs: np.ndarray           # last computed outputs (held, ZOH)
    step_observer: Callable[[float, Any], None]
    b_extra_fn: Callable[[float], list]
    n_fires: int = 0
    teardown: Optional[Callable[[], None]] = None


def _resolve_input(builder, wire) -> int:
    """Resolve an input wire to a state-vector index."""
    if not isinstance(wire, (tuple, list)) or len(wire) != 2:
        raise ValueError(
            f"c_block input wire must be ('v', node) or ('i', branch); "
            f"got {wire!r}")
    kind, name = wire[0], wire[1]
    if kind in _V_KINDS:
        return int(builder.node_id_of(name))
    if kind in _I_KINDS:
        bid = int(builder.branch_id_of(name))
        for fn_name in ("branch_var_id_for_inductor",
                        "branch_var_id_for_source"):
            try:
                idx = int(getattr(builder.pool, fn_name)(bid, builder.graph))
            except Exception:  # noqa: BLE001 — wrong family, try the next
                continue
            if idx >= 0:
                return idx
        raise ValueError(
            f"c_block input ('i', {name!r}): no current state variable — "
            f"only inductor and source currents are reconstructible.")
    raise ValueError(
        f"c_block input wire kind {kind!r} not in {_V_KINDS + _I_KINDS}")


def _add_output_source(builder, wire, src_name):
    """Create the controlled source for an output wire and return an
    injector ``(kind, *rows)`` describing how to write its value into
    ``b_extra``."""
    if not isinstance(wire, (tuple, list)) or len(wire) != 3:
        raise ValueError(
            f"c_block output wire must be ('v', n+, n-) or ('i', n+, n-); "
            f"got {wire!r}")
    kind, n_pos, n_neg = wire[0], wire[1], wire[2]
    if kind in _V_KINDS:
        builder.add_voltage_source(src_name, n_pos, n_neg, 0.0)
        bid = int(builder.branch_id_of(src_name))
        row = int(builder.pool.branch_var_id_for_source(bid, builder.graph))
        return ("v", row)
    if kind in _I_KINDS:
        builder.add_current_source(src_name, n_pos, n_neg, 0.0)
        # A current source has no augmented unknown; its value lands in
        # the two node KCL rows of the RHS. Ground (id < 0) is skipped.
        r_pos = int(builder.node_id_of(n_pos))
        r_neg = int(builder.node_id_of(n_neg))
        return ("i", r_pos, r_neg)
    raise ValueError(
        f"c_block output wire kind {kind!r} not in {_V_KINDS + _I_KINDS}")


_DBL = ctypes.POINTER(ctypes.c_double)
_STEP_ARGTYPES = [_DBL, ctypes.c_int, _DBL, ctypes.c_int,
                  ctypes.c_double, ctypes.c_double,
                  ctypes.POINTER(ctypes.c_void_p)]


def _load_native_step(lib_path, symbol, n_in, n_out, *,
                      init_symbol="pulsim_cblock_init",
                      term_symbol="pulsim_cblock_term"):
    """Load a compiled C-block library and return ``(step_fn, teardown)``.

    ``step_fn(t, dt, inp, out, _state)`` calls the C ABI, marshalling the
    numpy buffers as ``double*``; ``teardown()`` calls the optional
    ``term`` entry point. The CDLL + opaque state pointer are kept alive
    by the returned closures."""
    dll = ctypes.CDLL(str(lib_path))
    try:
        step_c = getattr(dll, symbol)
    except AttributeError as exc:
        raise ValueError(
            f"c_block: shared library {lib_path!r} does not export "
            f"{symbol!r} — check the symbol name (use extern \"C\" in "
            f"C++).") from exc
    step_c.restype = None
    step_c.argtypes = _STEP_ARGTYPES

    state_ptr = ctypes.c_void_p(None)
    if hasattr(dll, init_symbol):
        init_c = getattr(dll, init_symbol)
        init_c.restype = ctypes.c_void_p
        init_c.argtypes = [ctypes.c_int, ctypes.c_int]
        state_ptr = ctypes.c_void_p(init_c(int(n_in), int(n_out)))
    term_c = getattr(dll, term_symbol) if hasattr(dll, term_symbol) else None
    if term_c is not None:
        term_c.restype = None
        term_c.argtypes = [ctypes.c_void_p]

    def step(t, dt, inp, out, _state):
        step_c(inp.ctypes.data_as(_DBL), int(n_in),
               out.ctypes.data_as(_DBL), int(n_out),
               float(t), float(dt), ctypes.byref(state_ptr))

    def teardown():
        if term_c is not None and state_ptr.value:
            term_c(state_ptr)
            state_ptr.value = None

    step._dll = dll          # keep the library alive  # type: ignore[attr-defined]
    return step, teardown


def _find_compiler(lang: str):
    if lang in ("c",):
        cands = [os.environ.get("CC"), "cc", "gcc", "clang"]
    else:
        cands = [os.environ.get("CXX"), "c++", "g++", "clang++"]
    for c in cands:
        if c and shutil.which(c):
            return c
    return None


def _compile_inline(code: str, lang: str, symbol: str, *,
                    include_dirs=None, extra_compile_args=None,
                    extra_link_args=None) -> Path:
    """Compile inline C/C++ ``code`` (the function *body*) to a cached
    shared library and return its path. Raises if no compiler is found."""
    lang = {"c++": "cpp", "cxx": "cpp"}.get(lang.lower(), lang.lower())
    if lang not in ("c", "cpp"):
        raise ValueError(f"c_block: lang must be 'c' or 'cpp'; got {lang!r}")
    template = _C_TEMPLATE if lang == "c" else _CPP_TEMPLATE
    src = template.format(symbol=symbol, body=code)
    ext = ".c" if lang == "c" else ".cpp"

    compiler = _find_compiler(lang)
    if compiler is None:
        raise RuntimeError(
            "c_block: no C/C++ compiler found for inline source "
            f"(lang={lang!r}). Install a compiler, or pass a precompiled "
            "shared library via lib= instead.")
    flags = ["-shared", "-fPIC", "-O2"]
    flags += [f"-I{d}" for d in (include_dirs or [])]
    flags += list(extra_compile_args or [])
    link = list(extra_link_args or [])

    key = hashlib.sha256(
        "|".join([compiler, lang, symbol, src, *flags, *link]).encode()
    ).hexdigest()[:16]
    cache = Path(tempfile.gettempdir()) / "pulsim_cblock_cache"
    cache.mkdir(parents=True, exist_ok=True)
    so_path = cache / f"cblk_{key}.so"
    if so_path.exists():
        return so_path

    src_path = cache / f"cblk_{key}{ext}"
    src_path.write_text(src)
    cmd = [compiler, *flags, str(src_path), "-o", str(so_path), *link]
    try:
        subprocess.run(cmd, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(
            f"c_block: inline {lang} compile failed:\n"
            f"$ {' '.join(cmd)}\n{exc.stderr}") from None
    return so_path


def add_c_block(builder,
                inputs: Sequence,
                outputs: Sequence,
                *,
                dt: float,
                fn: Optional[Callable[..., Any]] = None,
                lib: Optional[str] = None,
                code: Optional[str] = None,
                lang: str = "c",
                symbol: str = "pulsim_cblock_step",
                include_dirs: Optional[Sequence[str]] = None,
                extra_compile_args: Optional[Sequence[str]] = None,
                extra_link_args: Optional[Sequence[str]] = None,
                name: str = "CBLK",
                state: Optional[dict] = None,
                sim_dt: Optional[float] = None) -> CBlockHandle:
    """Attach a custom-code block to ``builder`` (Python step fn, PWL).

    Parameters
    ----------
    builder
        The :class:`CircuitBuilder` (call after the circuit topology is
        complete — input wires and output sources are resolved now).
    inputs
        Input wires: each ``("v", node)`` or ``("i", branch)``.
    outputs
        Output wires: each ``("v", n+, n-)`` or ``("i", n+, n-)``; each
        creates one controlled source.
    dt
        Block sample time (s). The step fn fires at ``t=0`` and every
        ``dt`` thereafter; outputs are held (ZOH) in between. Must be
        ``>= sim dt`` (warns + clamps otherwise; pass ``sim_dt`` so the
        clamp check can run at add time).
    fn
        Python step function ``fn(t, dt, inp, out, state)`` where
        ``inp``/``out`` are length-N/M numpy buffers and ``state`` is a
        persistent dict. It may write ``out`` in place or ``return`` a
        length-M sequence. Exactly one of ``fn`` / ``lib`` / ``code`` is
        required.
    lib
        Path to a compiled shared library (``.so``/``.dll``/``.dylib``)
        exporting the C-block ABI (see :data:`CBLOCK_ABI`); loaded via
        ``ctypes``. C++ must use ``extern "C"``.
    code, lang
        Inline C (``lang="c"``) or C++ (``lang="cpp"``) **body** of the
        step function (with ``in``/``out``/``n_in``/``n_out``/``t``/``dt``/
        ``state`` in scope); compiled to a cached shared library with the
        system compiler and loaded via ``lib=``.
    symbol
        Exported step-function name in ``lib`` (default
        ``"pulsim_cblock_step"``).
    include_dirs, extra_compile_args, extra_link_args
        Passed through to the inline compiler.
    name
        Block name; output sources are named ``{name}_out{k}``.
    state
        Optional initial state dict (persists across steps).

    Returns
    -------
    CBlockHandle
        Registered on ``builder._c_blocks``; :func:`simulate` picks it up
        automatically — just call ``simulate(builder, ...)``.
    """
    inputs = list(inputs)
    outputs = list(outputs)
    n_in, n_out = len(inputs), len(outputs)
    if dt <= 0.0:
        raise ValueError(f"c_block dt must be > 0; got {dt}")
    if sim_dt is not None and dt < sim_dt:
        warnings.warn(
            f"c_block {name!r}: dt={dt:g}s < simulation dt={sim_dt:g}s; "
            f"clamping the block to run every simulation step.")
        dt = float(sim_dt)

    # Resolve the step function from exactly one of fn / lib / code.
    if sum(x is not None for x in (fn, lib, code)) != 1:
        raise ValueError(
            "add_c_block: provide exactly one of fn= (Python), lib= "
            "(compiled shared library), or code= (inline C/C++ source).")
    teardown: Optional[Callable[[], None]] = None
    if code is not None:
        lib = str(_compile_inline(
            code, lang, symbol, include_dirs=include_dirs,
            extra_compile_args=extra_compile_args,
            extra_link_args=extra_link_args))
    if lib is not None:
        fn, teardown = _load_native_step(lib, symbol, n_in, n_out)
    assert fn is not None

    in_locs = [_resolve_input(builder, w) for w in inputs]
    injectors = [_add_output_source(builder, w, f"{name}_out{k}")
                 for k, w in enumerate(outputs)]
    # state_size must be read AFTER the output sources are added.
    state_size = int(builder.pool.state_size(builder.graph))

    user_state: dict = dict(state) if state else {}
    inp_buf = np.zeros(n_in, dtype=float)
    out_buf = np.zeros(n_out, dtype=float)
    fire = {"last_t": None, "n": 0}

    def step_observer(t: float, x) -> None:
        last_t = fire["last_t"]
        if last_t is not None and (t - last_t) < dt - 1e-12:
            return  # ZOH — hold previous outputs
        for k, loc in enumerate(in_locs):
            inp_buf[k] = float(x[loc])
        ret = fn(float(t), float(dt), inp_buf, out_buf, user_state)
        if ret is not None:
            ret_arr = np.asarray(ret, dtype=float).ravel()
            if ret_arr.size != n_out:
                raise ValueError(
                    f"c_block {name!r}: step fn returned {ret_arr.size} "
                    f"values but the block has {n_out} outputs")
            out_buf[:] = ret_arr
        fire["last_t"] = t
        fire["n"] += 1

    def b_extra_fn(t: float) -> list:
        vec = [0.0] * state_size
        for k, inj in enumerate(injectors):
            val = float(out_buf[k])
            if inj[0] == "v":                       # voltage source: aug row
                vec[inj[1]] += _V_SRC_SIGN * val
            else:                                    # current source: node rows
                r_pos, r_neg = inj[1], inj[2]
                if 0 <= r_pos < state_size:
                    vec[r_pos] += _I_SRC_SIGN * val
                if 0 <= r_neg < state_size:
                    vec[r_neg] -= _I_SRC_SIGN * val
        return vec

    handle = CBlockHandle(
        name=name, n_in=n_in, n_out=n_out, dt_block=float(dt),
        state=user_state, inputs=inp_buf, outputs=out_buf,
        step_observer=step_observer, b_extra_fn=b_extra_fn,
        teardown=teardown)

    # Free native block state (term) when the handle is garbage-collected.
    if teardown is not None:
        weakref.finalize(handle, teardown)

    # Keep n_fires in sync for diagnostics.
    def _wrapped_observer(t, x, _orig=step_observer):
        _orig(t, x)
        handle.n_fires = fire["n"]
    handle.step_observer = _wrapped_observer

    if not hasattr(builder, "_c_blocks"):
        try:
            builder._c_blocks = []
        except Exception:  # noqa: BLE001 — builder may forbid attrs
            raise RuntimeError(
                "add_c_block: this builder does not accept dynamic "
                "attributes; cannot register the block.")
    builder._c_blocks.append(handle)
    return handle


def wire_c_blocks_from_yaml(loaded, spec, *,
                            sim_dt: Optional[float] = None) -> list:
    """Add one or more C blocks from a YAML / Python ``c_blocks`` spec.

    Parameters
    ----------
    loaded
        A ``LoadedCircuit`` (from :func:`pulsim.load_yaml_file` /
        :func:`pulsim.load_yaml_string`) or a bare ``CircuitBuilder``.
    spec
        A YAML string, or a Python list of dicts (or a dict with a
        top-level ``c_blocks:`` key). Each block has ``inputs``,
        ``outputs``, ``dt``, and the step code as either ``code`` +
        ``lang``, a source ``file`` + ``lang``, or a precompiled ``lib``.
        (Python ``fn`` callables can't be serialised, so YAML blocks use
        ``code`` / ``file`` / ``lib``.)

    Returns
    -------
    list[CBlockHandle]
    """
    builder = getattr(loaded, "builder", loaded)
    if isinstance(spec, str):
        try:
            import yaml as _yaml
        except ModuleNotFoundError as exc:
            raise ModuleNotFoundError(
                "wire_c_blocks_from_yaml: parsing a YAML string needs "
                "PyYAML (`pip install 'pulsim[dev]'`), or pass a Python "
                "list of dicts instead.") from exc
        blocks = _yaml.safe_load(spec)
    else:
        blocks = spec
    if blocks is None:
        return []
    if isinstance(blocks, dict):
        blocks = blocks.get("c_blocks", blocks)
    if not isinstance(blocks, list):
        raise ValueError(
            "c_blocks spec must be a list of mappings; got "
            f"{type(blocks).__name__}")

    handles = []
    for i, blk in enumerate(blocks):
        if not isinstance(blk, dict):
            raise ValueError(f"c_block #{i} must be a mapping")
        b = dict(blk)
        b.pop("type", None)
        inputs = [tuple(w) for w in b.pop("inputs", [])]
        outputs = [tuple(w) for w in b.pop("outputs", [])]
        if "dt" not in b:
            raise ValueError(f"c_block #{i} missing required field 'dt'")
        dt = float(b.pop("dt"))
        file = b.pop("file", None)
        if file is not None and "code" not in b:
            b["code"] = Path(file).read_text()
        bad = set(b) - _YAML_FIELDS
        if bad:
            raise ValueError(
                f"c_block #{i} has unknown field(s) {sorted(bad)}; "
                f"allowed: {sorted(_YAML_FIELDS | {'inputs', 'outputs', 'dt', 'file', 'type'})}")
        handles.append(add_c_block(builder, inputs, outputs,
                                   dt=dt, sim_dt=sim_dt, **b))
    return handles
