"""Modular Multilevel Converter (MMC) models.

Phase 20 — L0 of the layered MMC block hierarchy. This module ships the
**average-value arm model**: one state per arm (``v_C``, the sum of the
submodule capacitor voltages), continuous modulation index
``m_b ∈ [0, 1]`` (half-bridge) or ``m_b ∈ [-1, 1]`` (full-bridge), and
forward-Euler integration of the capacitor dynamics.

Reference
=========

Sousa, Gean Jacques Maia de.
*Sistemas de Controle para a Operação Eficiente de Conversores
Modulares Multiníveis em Acionamentos Elétricos.*
PhD thesis, UFSC, 2022. — ``artigos/Gean Jacques Maia de Sousa.pdf``

Average-arm equations (thesis eqs 2.13, 2.14)
=============================================

With per-submodule capacitance ``C_SM`` and ``N`` submodules per arm,
define the arm-equivalent capacitance ``C = C_SM / N`` and the
modulation index ``m_b = s_b / N`` (where ``s_b ∈ {0..N}`` is the
multilevel switching function). The averaged dynamics become

.. math::

    v_b = m_b \\cdot v_C
    \\\\
    \\frac{dv_C}{dt} = \\frac{1}{C} \\cdot m_b \\cdot i_b

with ``v_b`` the voltage generated by the arm and ``i_b`` the current
flowing through it.

This is mathematically identical to an *ideal transformer with turns
ratio* ``m_b : 1`` feeding the equivalent capacitor ``C`` (thesis
fig 2.6). L0 implements that abstraction directly as an explicit ODE
in Python.

API
===

* :class:`MmcArmAverageParams` — config (N, C_SM, type, initial v_C, ...).
* :class:`MmcArmAverageResult` — simulation output (time series).
* :func:`simulate_mmc_arm_average` — drive the average arm model
  over a duration with user-supplied ``m_b(t)`` and ``i_b(t)``.
* :func:`mmc_arm_average_step` — pure one-step advance (for users who
  want to embed the arm in their own outer loop).

The L1 (discrete multilevel), L2 (SM-equivalent with dead-time +
min-pulse-width), and L3 (per-SM detailed) blocks live in follow-up
phases. See ``docs/internals/mmc-arm-block.md`` for the full roadmap.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Literal

import numpy as np

__all__ = [
    "MmcArmAverageParams",
    "MmcArmAverageResult",
    "mmc_arm_average_step",
    "simulate_mmc_arm_average",
    # Builder-side wiring (Phase 20.4).
    "MmcArmAverage",
    "add_mmc_arm_average",
    "make_mmc_arm_observer",
    "make_mmc_arms_observer",
]


SubmoduleType = Literal["half_bridge", "full_bridge"]


# ----------------------------------------------------------------------
# Parameter contract
# ----------------------------------------------------------------------

@dataclass(frozen=True)
class MmcArmAverageParams:
    """Configuration for the L0 average-arm model.

    Attributes:
        n_sm: Number of submodules per arm (≥ 1).
        c_sm: Capacitance of one submodule [F]. The arm-equivalent
            capacitance is ``C = c_sm / n_sm``.
        sm_type: ``"half_bridge"`` (m_b ∈ [0, 1]) or
            ``"full_bridge"`` (m_b ∈ [-1, 1]).
        v_c0: Initial capacitor-sum voltage [V] (``v_C(0)``).
        r_p: Optional parallel loss resistance across the equivalent
            capacitor [Ω]. ``None`` (default) ⇒ lossless. When set, the
            dynamics become
            ``dv_C/dt = (m_b · i_b - v_C / r_p) / C``,
            matching thesis eq (3.99) sans the auxiliary-supply term.
    """

    n_sm: int
    c_sm: float
    sm_type: SubmoduleType = "half_bridge"
    v_c0: float = 0.0
    r_p: float | None = None

    def __post_init__(self) -> None:
        if self.n_sm < 1:
            raise ValueError(f"n_sm must be ≥ 1 (got {self.n_sm})")
        if self.c_sm <= 0:
            raise ValueError(f"c_sm must be > 0 (got {self.c_sm})")
        if self.sm_type not in ("half_bridge", "full_bridge"):
            raise ValueError(
                f"sm_type must be 'half_bridge' or 'full_bridge' "
                f"(got {self.sm_type!r})"
            )
        if self.r_p is not None and self.r_p <= 0:
            raise ValueError(f"r_p must be > 0 when set (got {self.r_p})")

    @property
    def c_arm(self) -> float:
        """Arm-equivalent capacitance C = c_sm / n_sm [F]."""
        return self.c_sm / self.n_sm

    @property
    def m_min(self) -> float:
        """Minimum valid modulation index (0 for HB, -1 for FB)."""
        return 0.0 if self.sm_type == "half_bridge" else -1.0

    @property
    def m_max(self) -> float:
        """Maximum valid modulation index (1 for both topologies)."""
        return 1.0


# ----------------------------------------------------------------------
# Step function — the single source of truth for the dynamics
# ----------------------------------------------------------------------

def mmc_arm_average_step(
    v_C: float,
    m_b: float,
    i_b: float,
    dt: float,
    params: MmcArmAverageParams,
) -> tuple[float, float]:
    """Advance the L0 average-arm model by one forward-Euler step.

    Args:
        v_C: Current arm-equivalent capacitor voltage [V].
        m_b: Modulation index for this step (range depends on
            ``params.sm_type``).
        i_b: Arm current at this step [A].
        dt: Time step [s] (must be > 0).
        params: Arm configuration.

    Returns:
        ``(v_C_next, v_b)``:
            * ``v_C_next`` — capacitor-sum voltage after ``dt``.
            * ``v_b`` — voltage generated by the arm at this step
              (``m_b · v_C``).

    Notes:
        Forward-Euler is sufficient for the average model because the
        capacitor pole sits at ``1 / (R_p · C)`` (typically << 1 kHz),
        far below typical simulation step rates. Use a smaller step
        only if you also resolve the high-frequency modulation content
        in ``m_b(t)``.
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")

    v_b = m_b * v_C
    # dv_C/dt = (m_b · i_b - v_C / R_p) / C
    leak = (v_C / params.r_p) if params.r_p is not None else 0.0
    dv_dt = (m_b * i_b - leak) / params.c_arm
    v_C_next = v_C + dt * dv_dt
    return v_C_next, v_b


# ----------------------------------------------------------------------
# Time-series driver
# ----------------------------------------------------------------------

@dataclass(frozen=True)
class MmcArmAverageResult:
    """Output of :func:`simulate_mmc_arm_average`.

    All arrays share the same shape ``(N + 1,)`` where ``N = duration / dt``
    (rounded).

    Attributes:
        t: Time vector [s].
        v_C: Capacitor-sum voltage trajectory [V].
        v_b: Arm-generated voltage trajectory [V].
        m_b: Applied modulation index trajectory.
        i_b: Arm current trajectory [A].
        params: Parameters used for the run (echoed for traceability).
    """

    t: np.ndarray
    v_C: np.ndarray
    v_b: np.ndarray
    m_b: np.ndarray
    i_b: np.ndarray
    params: MmcArmAverageParams = field(repr=False)


def simulate_mmc_arm_average(
    *,
    duration: float,
    dt: float,
    m_b: float | Callable[[float], float],
    i_b: float | Callable[[float], float],
    params: MmcArmAverageParams,
) -> MmcArmAverageResult:
    """Run the L0 average-arm model over ``[0, duration]``.

    Args:
        duration: Simulation length [s] (must be > 0).
        dt: Fixed time step [s] (must be > 0 and < duration).
        m_b: Modulation index. Pass a scalar for a constant signal or
            a callable ``t -> m_b`` for time-varying input.
        i_b: Arm current [A]. Same shape as ``m_b``: scalar or callable.
        params: Arm configuration.

    Returns:
        A :class:`MmcArmAverageResult` with the full trajectories.

    Raises:
        ValueError: If ``duration`` or ``dt`` are non-positive, or if
            ``m_b`` ever lies outside ``[params.m_min, params.m_max]``.
    """
    if duration <= 0:
        raise ValueError(f"duration must be > 0 (got {duration})")
    if dt <= 0 or dt > duration:
        raise ValueError(f"dt must be in (0, duration] (got {dt})")

    n_steps = int(np.floor(duration / dt))
    n_points = n_steps + 1
    t = np.arange(n_points) * dt

    m_b_fn = (lambda _t, _v=float(m_b): _v) if not callable(m_b) else m_b
    i_b_fn = (lambda _t, _v=float(i_b): _v) if not callable(i_b) else i_b

    v_C_arr = np.zeros(n_points)
    v_b_arr = np.zeros(n_points)
    m_b_arr = np.zeros(n_points)
    i_b_arr = np.zeros(n_points)

    v_C = float(params.v_c0)
    for k, tk in enumerate(t):
        m_k = float(m_b_fn(tk))
        i_k = float(i_b_fn(tk))
        if m_k < params.m_min or m_k > params.m_max:
            raise ValueError(
                f"m_b={m_k:.4f} at t={tk:.6f}s outside valid range "
                f"[{params.m_min}, {params.m_max}] for "
                f"sm_type={params.sm_type!r}"
            )
        m_b_arr[k] = m_k
        i_b_arr[k] = i_k
        v_C_arr[k] = v_C
        v_b_arr[k] = m_k * v_C
        if k < n_points - 1:
            v_C, _ = mmc_arm_average_step(v_C, m_k, i_k, dt, params)

    return MmcArmAverageResult(
        t=t,
        v_C=v_C_arr,
        v_b=v_b_arr,
        m_b=m_b_arr,
        i_b=i_b_arr,
        params=params,
    )


# ----------------------------------------------------------------------
# CircuitBuilder integration — Phase 20.4
# ----------------------------------------------------------------------
#
# Wiring strategy
# ---------------
# pulsim's VCVS has a constant gain. To express `v_b(t) = m_b(t)·v_C(t)`
# as a *time-varying* controlled source we follow the same trick the
# motor observers use (see ``motors.py``):
#
#   1. ``add_mmc_arm_average`` inserts a regular voltage source between
#      ``node_a`` (arm top) and ``node_b`` (arm bottom) with a baseline
#      of 0 V. The source records its branch ID so the observer can
#      later locate (a) its constraint row in the RHS vector, and
#      (b) its branch-current state index.
#
#   2. ``make_mmc_arm_observer`` returns a ``(step_observer, b_extra_fn)``
#      pair. At each simulation step:
#        * ``step_observer(t, x)`` reads the arm current from
#          ``x[src_idx]`` (the v-source branch variable), advances
#          ``v_C`` by one forward-Euler tick of eq (2.14), and stashes
#          ``v_b(t+dt) = m_b(t+dt) · v_C(t+dt)`` in a closure.
#        * ``b_extra_fn(t)`` returns a vector whose ``src_idx`` entry
#          equals ``−v_b(t)`` — pulsim's MNA convention is that adding
#          ``+X`` to the source's constraint row shifts the source
#          voltage by ``−X`` (see motor-observer doc-comment).
#
# This is *co-simulation* with the kernel rather than a stamped
# device — fine for L0 (one-pole capacitor, no event detection). L2+
# will need a proper C++ device because the dead-time monostables
# need sub-step resolution.


@dataclass
class MmcArmAverage:
    """Runtime state for an MMC average-value arm added to a circuit.

    Attributes are mutated by :func:`make_mmc_arm_observer` as the
    simulation progresses; user code can read ``v_C`` (and ``v_b``)
    at any point after a ``simulate()`` call.

    Attributes:
        params: Static configuration (capacitance, type, …).
        m_b_fn: Modulation-index signal ``t -> m_b ∈ [m_min, m_max]``.
        v_C: Live arm-equivalent capacitor voltage [V] (mutated each
            step). Starts at ``params.v_c0``.
        v_b: Live arm-generated voltage [V] (== m_b(t) · v_C). Mirrors
            what the observer stashes for the *next* simulation step.
        name: Prefix used for the underlying voltage-source name.
        source_branch_id: Graph branch id of the v-source added by
            :func:`add_mmc_arm_average` — needed to locate the state
            index of i_b.
    """

    params: MmcArmAverageParams
    m_b_fn: Callable[[float], float]
    v_C: float = 0.0
    v_b: float = 0.0
    name: str = ""
    source_branch_id: int = -1


def add_mmc_arm_average(
    builder,
    *,
    name: str,
    node_a: str,
    node_b: str,
    params: MmcArmAverageParams,
    m_b: float | Callable[[float], float],
) -> MmcArmAverage:
    """Add an MMC average-value arm to ``builder``.

    Topology:

        node_a ── (V_arm controlled = m_b·v_C) ── node_b

    The arm is exposed as a *single* voltage source whose value is
    updated each simulation step by the observer / b_extra_fn pair
    returned by :func:`make_mmc_arm_observer`. The user is
    responsible for adding any series arm inductor (``L_b``) and
    completing the rest of the topology.

    Args:
        builder: A populated ``pulsim.CircuitBuilder``.
        name: Prefix for the underlying voltage source — the source
            is registered as ``f"{name}_Varm"`` in the builder.
        node_a: Top terminal of the arm.
        node_b: Bottom terminal of the arm.
        params: Static arm configuration.
        m_b: Modulation-index signal. Scalar (constant) or callable
            ``t -> float``.

    Returns:
        An :class:`MmcArmAverage` carrying the live capacitor-voltage
        state and the source branch id.

    Notes:
        Pair the returned object with :func:`make_mmc_arm_observer`:

        .. code-block:: python

            arm = p.add_mmc_arm_average(b, ..., params=params, m_b=...)
            obs, bex = p.make_mmc_arm_observer(b, arm, dt=dt)
            res = p.simulate(b, t_end=..., dt=dt,
                             step_observer=obs, b_extra_fn=bex)
            print(arm.v_C)   # final capacitor voltage
    """
    m_b_fn: Callable[[float], float]
    if callable(m_b):
        m_b_fn = m_b
    else:
        m_b_const = float(m_b)
        m_b_fn = lambda _t, _v=m_b_const: _v  # noqa: E731

    # Validate the initial modulation index (cheap sanity check —
    # catches sign / topology mismatches at build time rather than
    # at first step).
    m0 = float(m_b_fn(0.0))
    if m0 < params.m_min or m0 > params.m_max:
        raise ValueError(
            f"m_b(t=0)={m0:.4f} outside valid range "
            f"[{params.m_min}, {params.m_max}] for "
            f"sm_type={params.sm_type!r}",
        )

    # Record branch id before adding (it equals the current branch
    # count — same trick motors.py uses).
    src_id = builder.graph.num_branches
    builder.add_voltage_source(f"{name}_Varm", node_a, node_b, 0.0)

    return MmcArmAverage(
        params=params,
        m_b_fn=m_b_fn,
        v_C=float(params.v_c0),
        v_b=m0 * float(params.v_c0),
        name=name,
        source_branch_id=src_id,
    )


def make_mmc_arm_observer(builder, arm: MmcArmAverage, *, dt: float):
    """Convenience single-arm wrapper around
    :func:`make_mmc_arms_observer`."""
    return make_mmc_arms_observer(builder, [arm], dt=dt)


def make_mmc_arms_observer(
    builder,
    arms: "list[MmcArmAverage]",
    *,
    dt: float,
):
    """Build a ``(step_observer, b_extra_fn)`` pair for one or more
    average-value MMC arms sharing the same simulation step.

    Args:
        builder: The :class:`pulsim.CircuitBuilder` that already has
            every arm registered via :func:`add_mmc_arm_average`.
        arms: Sequence of :class:`MmcArmAverage` objects (one per
            arm). Their order is irrelevant — each carries its own
            branch id.
        dt: Mechanical/electrical step in seconds. Must equal the
            ``dt`` you pass to :func:`pulsim.simulate`.

    Returns:
        ``(step_observer, b_extra_fn)`` ready to plug into
        :func:`pulsim.simulate`.

    Raises:
        ValueError: If ``dt`` is non-positive or ``arms`` is empty.

    Notes
    -----

    **Sign convention for ``i_b``.** pulsim's voltage-source branch
    variable carries the current that enters the source at its
    ``from`` node. The MMC convention used in
    :func:`mmc_arm_average_step` defines ``i_b`` as the current
    flowing in the *opposite* direction (out of ``node_a`` through
    the arm); the observer negates ``x[src_idx]`` accordingly.

    **Step-counting bias.** ``step_observer`` fires *once per sample*
    (``N + 1`` calls for ``N`` integration steps), advancing
    ``arm.v_C`` on every call. With ``start_from_dc_op=True`` the
    final value of ``arm.v_C`` therefore represents
    ``v_C(t_end + dt)`` rather than ``v_C(t_end)`` — a one-step
    forward-Euler offset (typically ≤ 0.1 % of the swing at L0 step
    rates). The pure-Python :func:`simulate_mmc_arm_average` does
    not have this bias because it doesn't hook into the kernel.

    **Runtime ``m_b`` range validation.** ``add_mmc_arm_average``
    validates ``m_b(0)`` at build time. The kernel silently swallows
    any :class:`ValueError` raised from inside ``step_observer``, so
    we do *not* re-check the range at every step — the cost would be
    paid in vain. Users with time-varying ``m_b`` are responsible
    for keeping it in range; mis-clamped values just produce
    physically inconsistent ``v_C`` evolution but won't crash.
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")
    if not arms:
        raise ValueError("arms must contain at least one element")

    state_size = builder.pool.state_size(builder.graph)
    src_indices = [
        builder.pool.branch_var_id_for_source(
            arm.source_branch_id, builder.graph,
        )
        for arm in arms
    ]

    def step_observer(t, x):
        for k, arm in enumerate(arms):
            # pulsim's voltage-source branch-current convention sees
            # `x[src_idx]` as the current entering the source at its
            # ``from`` node (== node_a). The L0 ``i_b`` is conventionally
            # defined as the current flowing *out* of node_a through the
            # arm (i.e. into the cap+SM stack), which is the opposite
            # sign — hence the negation. Empirically verified with a
            # constant-current probe (see commit message for details).
            i_b = -float(x[src_indices[k]])
            m_now = float(arm.m_b_fn(t))
            v_C_next, _ = mmc_arm_average_step(
                arm.v_C, m_now, i_b, dt, arm.params,
            )
            arm.v_C = v_C_next
            # Stash the value of v_b for the *next* sample (t + dt).
            # The b_extra_fn convention reads this stash one step later.
            m_next = float(arm.m_b_fn(t + dt))
            arm.v_b = m_next * v_C_next

    def b_extra_fn(_t):
        out = [0.0] * state_size
        # Convention (matches motors.py): the constraint row reads
        # ``(V_from − V_to) − V_source = 0``. Adding ``+X`` to b
        # shifts V_source by ``−X``, so we inject ``−v_b`` to set the
        # source's terminal voltage to ``+v_b``.
        for k, arm in enumerate(arms):
            out[src_indices[k]] = -arm.v_b
        return out

    return step_observer, b_extra_fn
