"""Modular Multilevel Converter (MMC) models.

Phase 20 — L0 of the layered MMC block hierarchy. This module ships the
**average-value arm model**: one state per arm (``v_C``, the sum of the
submodule capacitor voltages), continuous modulation index
``m_b ∈ [0, 1]`` (half-bridge) or ``m_b ∈ [-1, 1]`` (full-bridge), and
forward-Euler integration of the capacitor dynamics.

Reference
=========

Sousa, Gean Jacques Maia de.
*Sistemas de Controle para a Operação Eficiente de Conversores
Modulares Multiníveis em Acionamentos Elétricos.*
PhD thesis, UFSC, 2022. — ``artigos/Gean Jacques Maia de Sousa.pdf``

Average-arm equations (thesis eqs 2.13, 2.14)
=============================================

With per-submodule capacitance ``C_SM`` and ``N`` submodules per arm,
define the arm-equivalent capacitance ``C = C_SM / N`` and the
modulation index ``m_b = s_b / N`` (where ``s_b ∈ {0..N}`` is the
multilevel switching function). The averaged dynamics become

.. math::

    v_b = m_b \\cdot v_C
    \\\\
    \\frac{dv_C}{dt} = \\frac{1}{C} \\cdot m_b \\cdot i_b

with ``v_b`` the voltage generated by the arm and ``i_b`` the current
flowing through it.

This is mathematically identical to an *ideal transformer with turns
ratio* ``m_b : 1`` feeding the equivalent capacitor ``C`` (thesis
fig 2.6). L0 implements that abstraction directly as an explicit ODE
in Python.

API
===

* :class:`MmcArmAverageParams` — config (N, C_SM, type, initial v_C, ...).
* :class:`MmcArmAverageResult` — simulation output (time series).
* :func:`simulate_mmc_arm_average` — drive the average arm model
  over a duration with user-supplied ``m_b(t)`` and ``i_b(t)``.
* :func:`mmc_arm_average_step` — pure one-step advance (for users who
  want to embed the arm in their own outer loop).

The L1 (discrete multilevel), L2 (SM-equivalent with dead-time +
min-pulse-width), and L3 (per-SM detailed) blocks live in follow-up
phases. See ``docs/internals/mmc-arm-block.md`` for the full roadmap.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Literal

import numpy as np

# Phase 20.12 — all MMC step functions live in C++ now
# (``core/include/pulsim/mmc/arm.hpp``). The Python module is a thin
# orchestrator: dataclasses, builder helpers, observers, and
# time-series drivers all delegate the per-step math to the kernel.
# There is no pure-Python fallback by design: a single implementation
# is the only contract worth maintaining.
from ._pulsim import (  # type: ignore[import-not-found]
    _cpp_ps_pwm_switching_function as _cpp_ps_pwm,
    _cpp_mmc_arm_average_step as _cpp_avg_step,
    _cpp_mmc_arm_multilevel_step as _cpp_ml_step,
    _cpp_mmc_arm_equivalent_step as _cpp_eq_step,
    _cpp_mmc_arm_detailed_step as _cpp_dt_step,
)

__all__ = [
    "MmcArmAverageParams",
    "MmcArmAverageResult",
    "mmc_arm_average_step",
    "simulate_mmc_arm_average",
    # Builder-side wiring (Phase 20.4).
    "MmcArmAverage",
    "add_mmc_arm_average",
    "make_mmc_arm_observer",
    "make_mmc_arms_observer",
    # Three-phase DC/AC topology helper (Phase 20.4 step 2).
    "MmcThreePhaseDcAc",
    "add_mmc_three_phase_dc_ac",
    # L1 multilevel (discrete s_b) — Phase 20.5.
    "MmcArmMultilevelParams",
    "MmcArmMultilevelResult",
    "ps_pwm_switching_function",
    "mmc_arm_multilevel_step",
    "simulate_mmc_arm_multilevel",
    # L2 SM-equivalent (dead-time aware) — Phase 20.6.
    "MmcArmEquivalentParams",
    "MmcArmEquivalentState",
    "MmcArmEquivalentResult",
    "make_l2_state",
    "mmc_arm_equivalent_step",
    "simulate_mmc_arm_equivalent",
    # L3 detailed (per-SM v_C with sort-and-select balancing) — Phase 20.7.
    "MmcArmDetailedParams",
    "MmcArmDetailedState",
    "MmcArmDetailedResult",
    "make_l3_state",
    "mmc_arm_detailed_step",
    "simulate_mmc_arm_detailed",
    # Builder-integration for L1/L2/L3 — Phase 20.8.
    "MmcArmMultilevel",
    "add_mmc_arm_multilevel",
    "make_mmc_arm_multilevel_observer",
    "make_mmc_arm_multilevel_observers",
    "MmcArmEquivalent",
    "add_mmc_arm_equivalent",
    "make_mmc_arm_equivalent_observer",
    "make_mmc_arm_equivalent_observers",
    "MmcArmDetailed",
    "add_mmc_arm_detailed",
    "make_mmc_arm_detailed_observer",
    "make_mmc_arm_detailed_observers",
]


SubmoduleType = Literal["half_bridge", "full_bridge"]


# ----------------------------------------------------------------------
# Parameter contract
# ----------------------------------------------------------------------

@dataclass(frozen=True)
class MmcArmAverageParams:
    """Configuration for the L0 average-arm model.

    Attributes:
        n_sm: Number of submodules per arm (≥ 1).
        c_sm: Capacitance of one submodule [F]. The arm-equivalent
            capacitance is ``C = c_sm / n_sm``.
        sm_type: ``"half_bridge"`` (m_b ∈ [0, 1]) or
            ``"full_bridge"`` (m_b ∈ [-1, 1]).
        v_c0: Initial capacitor-sum voltage [V] (``v_C(0)``).
        r_p: Optional parallel loss resistance across the equivalent
            capacitor [Ω]. ``None`` (default) ⇒ lossless. When set, the
            dynamics become
            ``dv_C/dt = (m_b · i_b - v_C / r_p) / C``,
            matching thesis eq (3.99) sans the auxiliary-supply term.
    """

    n_sm: int
    c_sm: float
    sm_type: SubmoduleType = "half_bridge"
    v_c0: float = 0.0
    r_p: float | None = None

    def __post_init__(self) -> None:
        if self.n_sm < 1:
            raise ValueError(f"n_sm must be ≥ 1 (got {self.n_sm})")
        if self.c_sm <= 0:
            raise ValueError(f"c_sm must be > 0 (got {self.c_sm})")
        if self.sm_type not in ("half_bridge", "full_bridge"):
            raise ValueError(
                f"sm_type must be 'half_bridge' or 'full_bridge' "
                f"(got {self.sm_type!r})"
            )
        if self.r_p is not None and self.r_p <= 0:
            raise ValueError(f"r_p must be > 0 when set (got {self.r_p})")

    @property
    def c_arm(self) -> float:
        """Arm-equivalent capacitance C = c_sm / n_sm [F]."""
        return self.c_sm / self.n_sm

    @property
    def m_min(self) -> float:
        """Minimum valid modulation index (0 for HB, -1 for FB)."""
        return 0.0 if self.sm_type == "half_bridge" else -1.0

    @property
    def m_max(self) -> float:
        """Maximum valid modulation index (1 for both topologies)."""
        return 1.0


# ----------------------------------------------------------------------
# Step function — the single source of truth for the dynamics
# ----------------------------------------------------------------------

def mmc_arm_average_step(
    v_C: float,
    m_b: float,
    i_b: float,
    dt: float,
    params: MmcArmAverageParams,
) -> tuple[float, float]:
    """Advance the L0 average-arm model by one forward-Euler step.

    Args:
        v_C: Current arm-equivalent capacitor voltage [V].
        m_b: Modulation index for this step (range depends on
            ``params.sm_type``).
        i_b: Arm current at this step [A].
        dt: Time step [s] (must be > 0).
        params: Arm configuration.

    Returns:
        ``(v_C_next, v_b)``:
            * ``v_C_next`` — capacitor-sum voltage after ``dt``.
            * ``v_b`` — voltage generated by the arm at this step
              (``m_b · v_C``).

    Notes:
        Forward-Euler is sufficient for the average model because the
        capacitor pole sits at ``1 / (R_p · C)`` (typically << 1 kHz),
        far below typical simulation step rates. Use a smaller step
        only if you also resolve the high-frequency modulation content
        in ``m_b(t)``.
    """
    r_p_inv = (1.0 / params.r_p) if params.r_p is not None else 0.0
    v_C_next, v_b = _cpp_avg_step(
        float(v_C), float(m_b), float(i_b),
        float(dt), float(params.c_arm), float(r_p_inv),
    )
    return v_C_next, v_b


# ----------------------------------------------------------------------
# Time-series driver
# ----------------------------------------------------------------------

@dataclass(frozen=True)
class MmcArmAverageResult:
    """Output of :func:`simulate_mmc_arm_average`.

    All arrays share the same shape ``(N + 1,)`` where ``N = duration / dt``
    (rounded).

    Attributes:
        t: Time vector [s].
        v_C: Capacitor-sum voltage trajectory [V].
        v_b: Arm-generated voltage trajectory [V].
        m_b: Applied modulation index trajectory.
        i_b: Arm current trajectory [A].
        params: Parameters used for the run (echoed for traceability).
    """

    t: np.ndarray
    v_C: np.ndarray
    v_b: np.ndarray
    m_b: np.ndarray
    i_b: np.ndarray
    params: MmcArmAverageParams = field(repr=False)


def simulate_mmc_arm_average(
    *,
    duration: float,
    dt: float,
    m_b: float | Callable[[float], float],
    i_b: float | Callable[[float], float],
    params: MmcArmAverageParams,
) -> MmcArmAverageResult:
    """Run the L0 average-arm model over ``[0, duration]``.

    Args:
        duration: Simulation length [s] (must be > 0).
        dt: Fixed time step [s] (must be > 0 and < duration).
        m_b: Modulation index. Pass a scalar for a constant signal or
            a callable ``t -> m_b`` for time-varying input.
        i_b: Arm current [A]. Same shape as ``m_b``: scalar or callable.
        params: Arm configuration.

    Returns:
        A :class:`MmcArmAverageResult` with the full trajectories.

    Raises:
        ValueError: If ``duration`` or ``dt`` are non-positive, or if
            ``m_b`` ever lies outside ``[params.m_min, params.m_max]``.
    """
    if duration <= 0:
        raise ValueError(f"duration must be > 0 (got {duration})")
    if dt <= 0 or dt > duration:
        raise ValueError(f"dt must be in (0, duration] (got {dt})")

    n_steps = int(np.floor(duration / dt))
    n_points = n_steps + 1
    t = np.arange(n_points) * dt

    m_b_fn = (lambda _t, _v=float(m_b): _v) if not callable(m_b) else m_b
    i_b_fn = (lambda _t, _v=float(i_b): _v) if not callable(i_b) else i_b

    v_C_arr = np.zeros(n_points)
    v_b_arr = np.zeros(n_points)
    m_b_arr = np.zeros(n_points)
    i_b_arr = np.zeros(n_points)

    v_C = float(params.v_c0)
    for k, tk in enumerate(t):
        m_k = float(m_b_fn(tk))
        i_k = float(i_b_fn(tk))
        if m_k < params.m_min or m_k > params.m_max:
            raise ValueError(
                f"m_b={m_k:.4f} at t={tk:.6f}s outside valid range "
                f"[{params.m_min}, {params.m_max}] for "
                f"sm_type={params.sm_type!r}"
            )
        m_b_arr[k] = m_k
        i_b_arr[k] = i_k
        v_C_arr[k] = v_C
        v_b_arr[k] = m_k * v_C
        if k < n_points - 1:
            v_C, _ = mmc_arm_average_step(v_C, m_k, i_k, dt, params)

    return MmcArmAverageResult(
        t=t,
        v_C=v_C_arr,
        v_b=v_b_arr,
        m_b=m_b_arr,
        i_b=i_b_arr,
        params=params,
    )


# ----------------------------------------------------------------------
# CircuitBuilder integration — Phase 20.4
# ----------------------------------------------------------------------
#
# Wiring strategy
# ---------------
# pulsim's VCVS has a constant gain. To express `v_b(t) = m_b(t)·v_C(t)`
# as a *time-varying* controlled source we follow the same trick the
# motor observers use (see ``motors.py``):
#
#   1. ``add_mmc_arm_average`` inserts a regular voltage source between
#      ``node_a`` (arm top) and ``node_b`` (arm bottom) with a baseline
#      of 0 V. The source records its branch ID so the observer can
#      later locate (a) its constraint row in the RHS vector, and
#      (b) its branch-current state index.
#
#   2. ``make_mmc_arm_observer`` returns a ``(step_observer, b_extra_fn)``
#      pair. At each simulation step:
#        * ``step_observer(t, x)`` reads the arm current from
#          ``x[src_idx]`` (the v-source branch variable), advances
#          ``v_C`` by one forward-Euler tick of eq (2.14), and stashes
#          ``v_b(t+dt) = m_b(t+dt) · v_C(t+dt)`` in a closure.
#        * ``b_extra_fn(t)`` returns a vector whose ``src_idx`` entry
#          equals ``−v_b(t)`` — pulsim's MNA convention is that adding
#          ``+X`` to the source's constraint row shifts the source
#          voltage by ``−X`` (see motor-observer doc-comment).
#
# This is *co-simulation* with the kernel rather than a stamped
# device — fine for L0 (one-pole capacitor, no event detection). L2+
# will need a proper C++ device because the dead-time monostables
# need sub-step resolution.


@dataclass
class MmcArmAverage:
    """Runtime state for an MMC average-value arm added to a circuit.

    Attributes are mutated by :func:`make_mmc_arm_observer` as the
    simulation progresses; user code can read ``v_C`` (and ``v_b``)
    at any point after a ``simulate()`` call.

    Attributes:
        params: Static configuration (capacitance, type, …).
        m_b_fn: Modulation-index signal ``t -> m_b ∈ [m_min, m_max]``.
        v_C: Live arm-equivalent capacitor voltage [V] (mutated each
            step). Starts at ``params.v_c0``.
        v_b: Live arm-generated voltage [V] (== m_b(t) · v_C). Mirrors
            what the observer stashes for the *next* simulation step.
        v_b_baseline: V-source baseline (== m_b(0) · v_c0) written
            into ``builder.add_voltage_source`` so DC-OP sees the
            correct arm voltage and can solve circuits with multiple
            arms in series (e.g. a 3-φ MMC).
        name: Prefix used for the underlying voltage-source name.
        source_branch_id: Graph branch id of the v-source added by
            :func:`add_mmc_arm_average` — needed to locate the state
            index of i_b.
    """

    params: MmcArmAverageParams
    m_b_fn: Callable[[float], float]
    v_C: float = 0.0
    v_b: float = 0.0
    v_b_baseline: float = 0.0
    name: str = ""
    source_branch_id: int = -1


def add_mmc_arm_average(
    builder,
    *,
    name: str,
    node_a: str,
    node_b: str,
    params: MmcArmAverageParams,
    m_b: float | Callable[[float], float],
) -> MmcArmAverage:
    """Add an MMC average-value arm to ``builder``.

    Topology:

        node_a ── (V_arm controlled = m_b·v_C) ── node_b

    The arm is exposed as a *single* voltage source whose value is
    updated each simulation step by the observer / b_extra_fn pair
    returned by :func:`make_mmc_arm_observer`. The user is
    responsible for adding any series arm inductor (``L_b``) and
    completing the rest of the topology.

    Args:
        builder: A populated ``pulsim.CircuitBuilder``.
        name: Prefix for the underlying voltage source — the source
            is registered as ``f"{name}_Varm"`` in the builder.
        node_a: Top terminal of the arm.
        node_b: Bottom terminal of the arm.
        params: Static arm configuration.
        m_b: Modulation-index signal. Scalar (constant) or callable
            ``t -> float``.

    Returns:
        An :class:`MmcArmAverage` carrying the live capacitor-voltage
        state and the source branch id.

    Notes:
        Pair the returned object with :func:`make_mmc_arm_observer`:

        .. code-block:: python

            arm = p.add_mmc_arm_average(b, ..., params=params, m_b=...)
            obs, bex = p.make_mmc_arm_observer(b, arm, dt=dt)
            res = p.simulate(b, t_end=..., dt=dt,
                             step_observer=obs, b_extra_fn=bex)
            print(arm.v_C)   # final capacitor voltage
    """
    m_b_fn: Callable[[float], float]
    if callable(m_b):
        m_b_fn = m_b
    else:
        m_b_const = float(m_b)
        m_b_fn = lambda _t, _v=m_b_const: _v  # noqa: E731

    # Validate the initial modulation index (cheap sanity check —
    # catches sign / topology mismatches at build time rather than
    # at first step).
    m0 = float(m_b_fn(0.0))
    if m0 < params.m_min or m0 > params.m_max:
        raise ValueError(
            f"m_b(t=0)={m0:.4f} outside valid range "
            f"[{params.m_min}, {params.m_max}] for "
            f"sm_type={params.sm_type!r}",
        )

    # Set the v-source baseline to m_b(0)·v_c0 so the kernel's
    # *DC operating point* solver sees the correct arm voltage at
    # t=0 — without this, multi-arm topologies (e.g. a 3-φ MMC where
    # the arms are arranged in series across the DC bus) make DC-OP
    # un-solvable and fall back to ill-conditioned states. The
    # observer's b_extra_fn then injects the *delta* from this
    # baseline at every subsequent step.
    v_b_baseline = m0 * float(params.v_c0)

    src_id = builder.graph.num_branches
    builder.add_voltage_source(
        f"{name}_Varm", node_a, node_b, v_b_baseline,
    )

    return MmcArmAverage(
        params=params,
        m_b_fn=m_b_fn,
        v_C=float(params.v_c0),
        v_b=v_b_baseline,
        v_b_baseline=v_b_baseline,
        name=name,
        source_branch_id=src_id,
    )


def make_mmc_arm_observer(builder, arm: MmcArmAverage, *, dt: float):
    """Convenience single-arm wrapper around
    :func:`make_mmc_arms_observer`."""
    return make_mmc_arms_observer(builder, [arm], dt=dt)


def make_mmc_arms_observer(
    builder,
    arms: "list[MmcArmAverage]",
    *,
    dt: float,
):
    """Build a ``(step_observer, b_extra_fn)`` pair for one or more
    average-value MMC arms sharing the same simulation step.

    Args:
        builder: The :class:`pulsim.CircuitBuilder` that already has
            every arm registered via :func:`add_mmc_arm_average`.
        arms: Sequence of :class:`MmcArmAverage` objects (one per
            arm). Their order is irrelevant — each carries its own
            branch id.
        dt: Mechanical/electrical step in seconds. Must equal the
            ``dt`` you pass to :func:`pulsim.simulate`.

    Returns:
        ``(step_observer, b_extra_fn)`` ready to plug into
        :func:`pulsim.simulate`.

    Raises:
        ValueError: If ``dt`` is non-positive or ``arms`` is empty.

    Notes
    -----

    **Sign convention for ``i_b``.** pulsim's voltage-source branch
    variable carries the current that enters the source at its
    ``from`` node. The MMC convention used in
    :func:`mmc_arm_average_step` defines ``i_b`` as the current
    flowing in the *opposite* direction (out of ``node_a`` through
    the arm); the observer negates ``x[src_idx]`` accordingly.

    **Step-counting bias.** ``step_observer`` fires *once per sample*
    (``N + 1`` calls for ``N`` integration steps), advancing
    ``arm.v_C`` on every call. With ``start_from_dc_op=True`` the
    final value of ``arm.v_C`` therefore represents
    ``v_C(t_end + dt)`` rather than ``v_C(t_end)`` — a one-step
    forward-Euler offset (typically ≤ 0.1 % of the swing at L0 step
    rates). The pure-Python :func:`simulate_mmc_arm_average` does
    not have this bias because it doesn't hook into the kernel.

    **Runtime ``m_b`` range validation.** ``add_mmc_arm_average``
    validates ``m_b(0)`` at build time. The kernel silently swallows
    any :class:`ValueError` raised from inside ``step_observer``, so
    we do *not* re-check the range at every step — the cost would be
    paid in vain. Users with time-varying ``m_b`` are responsible
    for keeping it in range; mis-clamped values just produce
    physically inconsistent ``v_C`` evolution but won't crash.
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")
    if not arms:
        raise ValueError("arms must contain at least one element")

    state_size = builder.pool.state_size(builder.graph)
    src_indices = [
        builder.pool.branch_var_id_for_source(
            arm.source_branch_id, builder.graph,
        )
        for arm in arms
    ]

    def step_observer(t, x):
        for k, arm in enumerate(arms):
            # pulsim's voltage-source branch-current convention:
            # ``x[src_idx]`` is positive when the internal current
            # flows in the ``from → to`` direction. The L0 physical
            # ``i_b`` (current charging the SM caps when m_b > 0) is
            # defined as the current entering the arm at ``node_a``
            # and exiting at ``node_b``, which is also the
            # ``from → to`` direction. So no negation is needed:
            # ``i_b`` is read directly from ``x[src_idx]``.
            #
            # Pinned down empirically with two probes:
            #   1. V-source / resistor pair under known V/R → x[src]
            #      = -I_R (positive when internal current is gnd→top
            #      for V("top","gnd",V), i.e. "from→to" wrt the
            #      source from=top, to=gnd ⇒ x[src] tracks
            #      "from→to" sign).
            #   2. 3-phase MMC at DC OP: x[src] on arm_b_p comes out
            #      with sign matching the analytically computed
            #      load-driven current.
            i_b = float(x[src_indices[k]])
            m_now = float(arm.m_b_fn(t))
            v_C_next, _ = mmc_arm_average_step(
                arm.v_C, m_now, i_b, dt, arm.params,
            )
            arm.v_C = v_C_next
            # Stash the value of v_b for the *next* sample (t + dt).
            # The b_extra_fn convention reads this stash one step later.
            m_next = float(arm.m_b_fn(t + dt))
            arm.v_b = m_next * v_C_next

    def b_extra_fn(_t):
        out = [0.0] * state_size
        # Convention (matches motors.py): the constraint row reads
        # ``(V_from − V_to) − V_source = 0``. Adding ``+X`` to b
        # shifts V_source by ``−X``. The v-source's *baseline* value
        # (set in ``add_mmc_arm_average``) is ``v_b_baseline`` =
        # m_b(0)·v_c0, so we inject the *delta* needed to bring the
        # effective source voltage to the current v_b:
        #   V_source_effective = baseline - inject(t) = v_b(t)
        #   ⇒ inject(t) = baseline - v_b(t)
        # At t=0 the inject is 0 (V_source stays at the DC-OP-correct
        # baseline); at later steps it tracks v_b(t).
        for k, arm in enumerate(arms):
            out[src_indices[k]] = arm.v_b_baseline - arm.v_b
        return out

    return step_observer, b_extra_fn


# ----------------------------------------------------------------------
# Three-phase DC/AC MMC topology helper (Phase 20.4 step 2)
# ----------------------------------------------------------------------
#
# Canonical topology (thesis fig 2.7):
#
#                       dc_pos
#                         │
#               ┌─────────┼─────────┐
#               │         │         │
#           [arm_a_p] [arm_b_p] [arm_c_p]   (upper arms — controlled VS)
#               │         │         │
#             L_a_p     L_b_p     L_c_p     (arm inductors)
#               │         │         │
#              ac_a      ac_b      ac_c     (AC ports)
#               │         │         │
#             L_a_n     L_b_n     L_c_n     (arm inductors)
#               │         │         │
#           [arm_a_n] [arm_b_n] [arm_c_n]   (lower arms — controlled VS)
#               │         │         │
#               └─────────┼─────────┘
#                         │
#                       dc_neg
#
# We do NOT add the DC bus voltage source — the user wires it
# externally (e.g. ``b.add_voltage_source("Vdc", "dc_pos", "dc_neg", V)``).
# We do NOT add an AC load — the user wires it between the three
# ``ac_nodes`` (e.g. a three-phase RL motor or a Y-connected grid
# impedance via :func:`pulsim.add_three_phase_grid`).


@dataclass
class MmcThreePhaseDcAc:
    """The six arms of a three-phase DC/AC MMC built by
    :func:`add_mmc_three_phase_dc_ac`.

    Each ``arm_*_p`` / ``arm_*_n`` is a live :class:`MmcArmAverage`
    whose ``v_C`` and ``v_b`` mutate as the simulation progresses.

    Attributes:
        arm_a_p, arm_b_p, arm_c_p: Upper arms (dc_pos → mid_X).
        arm_a_n, arm_b_n, arm_c_n: Lower arms (mid_X → dc_neg).
    """
    arm_a_p: MmcArmAverage
    arm_b_p: MmcArmAverage
    arm_c_p: MmcArmAverage
    arm_a_n: MmcArmAverage
    arm_b_n: MmcArmAverage
    arm_c_n: MmcArmAverage

    @property
    def all_arms(self) -> "list[MmcArmAverage]":
        """All six arms in (a_p, b_p, c_p, a_n, b_n, c_n) order."""
        return [
            self.arm_a_p, self.arm_b_p, self.arm_c_p,
            self.arm_a_n, self.arm_b_n, self.arm_c_n,
        ]

    @property
    def upper_arms(self) -> "list[MmcArmAverage]":
        """The three upper arms (positive DC-bus side)."""
        return [self.arm_a_p, self.arm_b_p, self.arm_c_p]

    @property
    def lower_arms(self) -> "list[MmcArmAverage]":
        """The three lower arms (negative DC-bus side)."""
        return [self.arm_a_n, self.arm_b_n, self.arm_c_n]


def add_mmc_three_phase_dc_ac(
    builder,
    *,
    name: str = "MMC",
    dc_pos: str,
    dc_neg: str,
    ac_nodes: "tuple[str, str, str]",
    n_sm: int,
    c_sm: float,
    l_b: float,
    sm_type: SubmoduleType = "half_bridge",
    v_c0: float = 0.0,
    m_signals: "tuple[Callable[[float], float] | float, ...]",
) -> MmcThreePhaseDcAc:
    """Add a complete three-phase DC/AC MMC topology to ``builder``.

    Composes:
        * Six average-value arms via :func:`add_mmc_arm_average`.
        * Six arm inductors of value ``l_b`` (Henries).

    The DC bus voltage source and the AC load are **not** added —
    wire them yourself before / after this helper.

    Args:
        builder: A populated ``pulsim.CircuitBuilder``.
        name: Common prefix for the device names registered (default
            ``"MMC"`` → ``MMC_a_p_Varm``, ``MMC_L_a_p``, …).
        dc_pos, dc_neg: Node names of the DC bus (positive and
            negative rails).
        ac_nodes: 3-tuple ``(ac_a, ac_b, ac_c)`` of node names for
            the three AC ports.
        n_sm, c_sm, sm_type, v_c0: Per-arm parameters forwarded into
            :class:`MmcArmAverageParams`. All six arms share the
            same values — for non-uniform arms, build them one at a
            time with :func:`add_mmc_arm_average`.
        l_b: Arm inductance in Henries (same for all six arms).
        m_signals: Either:
            * a 3-tuple ``(m_a, m_b, m_c)`` — applied to the upper
              arms; lower arms get the complement ``1 - m_X`` for
              half-bridge or ``-m_X`` for full-bridge so the arm
              sum ``v_arm_p + v_arm_n = v_C_p + v_C_n`` matches the
              DC bus by construction;
            * a 6-tuple ``(m_a_p, m_b_p, m_c_p, m_a_n, m_b_n, m_c_n)``
              — independent control of each arm.

    Returns:
        A :class:`MmcThreePhaseDcAc` carrying the six arm objects.

    Notes:
        Pair the returned object with :func:`make_mmc_arms_observer`:

        .. code-block:: python

            mmc = p.add_mmc_three_phase_dc_ac(b, ..., m_signals=...)
            obs, bex = p.make_mmc_arms_observer(
                b, mmc.all_arms, dt=dt,
            )
            res = p.simulate(b, ..., step_observer=obs,
                             b_extra_fn=bex,
                             start_from_dc_op=True)
    """
    if len(ac_nodes) != 3:
        raise ValueError(
            f"ac_nodes must be a 3-tuple (got len {len(ac_nodes)})",
        )
    if l_b <= 0:
        raise ValueError(f"l_b must be > 0 (got {l_b})")

    # Normalise m_signals → 6-tuple ``(m_a_p, m_b_p, m_c_p, m_a_n,
    # m_b_n, m_c_n)``.
    if len(m_signals) == 3:
        m_a, m_b_, m_c = m_signals  # type: ignore[misc]
        if sm_type == "half_bridge":
            def _complement(m_fn):
                if callable(m_fn):
                    return lambda t, _f=m_fn: 1.0 - float(_f(t))
                _const = float(m_fn)
                return lambda _t, _v=1.0 - _const: _v
        else:  # full_bridge
            def _complement(m_fn):
                if callable(m_fn):
                    return lambda t, _f=m_fn: -float(_f(t))
                _const = float(m_fn)
                return lambda _t, _v=-_const: _v
        m_signals = (
            m_a, m_b_, m_c,
            _complement(m_a), _complement(m_b_), _complement(m_c),
        )
    elif len(m_signals) != 6:
        raise ValueError(
            f"m_signals must be a 3- or 6-tuple (got len {len(m_signals)})",
        )

    m_a_p, m_b_p, m_c_p, m_a_n, m_b_n, m_c_n = m_signals
    ac_a, ac_b, ac_c = ac_nodes

    params = MmcArmAverageParams(
        n_sm=n_sm, c_sm=c_sm, sm_type=sm_type, v_c0=v_c0,
    )

    # --- Upper half: dc_pos → arm → mid → L_b → ac_X ---
    mid_a_p = f"{name}_mid_a_p"
    mid_b_p = f"{name}_mid_b_p"
    mid_c_p = f"{name}_mid_c_p"
    arm_a_p = add_mmc_arm_average(
        builder, name=f"{name}_a_p",
        node_a=dc_pos, node_b=mid_a_p,
        params=params, m_b=m_a_p,
    )
    arm_b_p = add_mmc_arm_average(
        builder, name=f"{name}_b_p",
        node_a=dc_pos, node_b=mid_b_p,
        params=params, m_b=m_b_p,
    )
    arm_c_p = add_mmc_arm_average(
        builder, name=f"{name}_c_p",
        node_a=dc_pos, node_b=mid_c_p,
        params=params, m_b=m_c_p,
    )
    builder.add_inductor(f"{name}_L_a_p", mid_a_p, ac_a, l_b)
    builder.add_inductor(f"{name}_L_b_p", mid_b_p, ac_b, l_b)
    builder.add_inductor(f"{name}_L_c_p", mid_c_p, ac_c, l_b)

    # --- Lower half: ac_X → L_b → mid → arm → dc_neg ---
    mid_a_n = f"{name}_mid_a_n"
    mid_b_n = f"{name}_mid_b_n"
    mid_c_n = f"{name}_mid_c_n"
    builder.add_inductor(f"{name}_L_a_n", ac_a, mid_a_n, l_b)
    builder.add_inductor(f"{name}_L_b_n", ac_b, mid_b_n, l_b)
    builder.add_inductor(f"{name}_L_c_n", ac_c, mid_c_n, l_b)
    arm_a_n = add_mmc_arm_average(
        builder, name=f"{name}_a_n",
        node_a=mid_a_n, node_b=dc_neg,
        params=params, m_b=m_a_n,
    )
    arm_b_n = add_mmc_arm_average(
        builder, name=f"{name}_b_n",
        node_a=mid_b_n, node_b=dc_neg,
        params=params, m_b=m_b_n,
    )
    arm_c_n = add_mmc_arm_average(
        builder, name=f"{name}_c_n",
        node_a=mid_c_n, node_b=dc_neg,
        params=params, m_b=m_c_n,
    )

    return MmcThreePhaseDcAc(
        arm_a_p=arm_a_p, arm_b_p=arm_b_p, arm_c_p=arm_c_p,
        arm_a_n=arm_a_n, arm_b_n=arm_b_n, arm_c_n=arm_c_n,
    )


# ======================================================================
# L1 — Multilevel arm model (discrete s_b ∈ {0..N}, PS-PWM)  Phase 20.5
# ======================================================================
#
# L1 keeps the *same* one-state-per-arm dynamics as L0 (eqs 2.7/2.9) but
# replaces the continuous modulation index ``m_b ∈ [0, 1]`` with a
# *quantized* switching count ``s_b ∈ {0, 1, …, N}``. Per the thesis:
#
#   v_b(t)      = (s_b(t) / N) · v_C(t)            (2.7)
#   dv_C/dt    = (1 / C_SM) · s_b(t) · i_b(t)     (2.9)
#
# Substituting ``m_b ≡ s_b/N`` and ``C_arm = C_SM/N`` recovers eq (2.14)
# of L0 — the dynamics are mathematically identical; the *only* new
# physics is the time-varying staircase ``s_b(t)`` generated by the
# multilevel modulator. We start with **phase-shifted PWM** (PS-PWM,
# the standard MMC modulation scheme): ``N`` triangular carriers, each
# offset by ``2π/N`` from the next, individually compared against the
# reference ``m_ref ∈ [0, 1]``. Effective arm-side switching frequency
# is ``N · f_carrier``.
#
# For full-bridge SMs the comparator threshold becomes ``|m_ref|`` and
# the sign of ``s_b`` follows ``sign(m_ref)``.


@dataclass(frozen=True)
class MmcArmMultilevelParams:
    """Configuration for the L1 multilevel-arm model.

    Same physical parameters as :class:`MmcArmAverageParams` plus the
    PS-PWM carrier frequency.

    Attributes:
        n_sm: Number of submodules per arm (≥ 1).
        c_sm: Per-SM capacitance [F]. ``C_arm = c_sm / n_sm``.
        sm_type: ``"half_bridge"`` (s_b ∈ {0..N}) or
            ``"full_bridge"`` (s_b ∈ {−N..N}).
        v_c0: Initial capacitor-sum voltage [V].
        r_p: Optional parallel loss resistance [Ω].
        f_carrier: PS-PWM carrier frequency per SM [Hz]. Each of the
            ``n_sm`` carriers runs at this frequency; the effective
            arm-side switching frequency is ``n_sm · f_carrier``.
    """

    n_sm: int
    c_sm: float
    sm_type: SubmoduleType = "half_bridge"
    v_c0: float = 0.0
    r_p: float | None = None
    f_carrier: float = 1000.0

    def __post_init__(self) -> None:
        if self.n_sm < 1:
            raise ValueError(f"n_sm must be ≥ 1 (got {self.n_sm})")
        if self.c_sm <= 0:
            raise ValueError(f"c_sm must be > 0 (got {self.c_sm})")
        if self.sm_type not in ("half_bridge", "full_bridge"):
            raise ValueError(
                f"sm_type must be 'half_bridge' or 'full_bridge' "
                f"(got {self.sm_type!r})",
            )
        if self.r_p is not None and self.r_p <= 0:
            raise ValueError(f"r_p must be > 0 when set (got {self.r_p})")
        if self.f_carrier <= 0:
            raise ValueError(
                f"f_carrier must be > 0 (got {self.f_carrier})",
            )

    @property
    def c_arm(self) -> float:
        """Arm-equivalent capacitance C_arm = c_sm / n_sm [F]."""
        return self.c_sm / self.n_sm

    @property
    def f_switch(self) -> float:
        """Effective arm-side switching frequency = n_sm · f_carrier."""
        return self.n_sm * self.f_carrier

    @property
    def m_min(self) -> float:
        return 0.0 if self.sm_type == "half_bridge" else -1.0

    @property
    def m_max(self) -> float:
        return 1.0


# ----------------------------------------------------------------------
# PS-PWM quantizer
# ----------------------------------------------------------------------

def ps_pwm_switching_function(
    m_ref: float,
    t: float,
    n_sm: int,
    f_carrier: float,
    *,
    sm_type: SubmoduleType = "half_bridge",
) -> int:
    """Phase-shifted PWM switching function ``s_b(t)``.

    Each of the ``n_sm`` SMs is gated by a triangular carrier of
    frequency ``f_carrier``, phase-shifted by ``2π · k / n_sm`` from
    the next. The SM bit fires while ``m_ref > carrier``; the sum of
    bits is the switching count ``s_b``.

    Args:
        m_ref: Reference modulation index ``∈ [0, 1]`` (HB) or
            ``[−1, 1]`` (FB). Out-of-range values are clamped to the
            nearest extreme (no exception — this is a hot-loop helper).
        t: Time [s].
        n_sm: Number of carriers (= number of SMs).
        f_carrier: Carrier frequency [Hz].
        sm_type: ``"half_bridge"`` ⇒ s_b ∈ {0..N}; ``"full_bridge"``
            ⇒ s_b ∈ {−N..N} with sign following ``m_ref``.

    Returns:
        ``s_b`` — integer switching count.
    """
    return int(_cpp_ps_pwm(
        float(m_ref), float(t), int(n_sm),
        float(f_carrier), sm_type,
    ))


# ----------------------------------------------------------------------
# Step + driver
# ----------------------------------------------------------------------

def mmc_arm_multilevel_step(
    v_C: float,
    m_ref: float,
    i_b: float,
    dt: float,
    t: float,
    params: MmcArmMultilevelParams,
) -> "tuple[float, float, int]":
    """Advance the L1 multilevel arm by one forward-Euler step.

    Args:
        v_C: Current arm-equivalent capacitor voltage [V].
        m_ref: Reference modulation index for this step (continuous).
        i_b: Arm current at this step [A].
        dt: Time step [s] (must be > 0).
        t: Current time [s] (needed to evaluate carriers).
        params: Arm configuration.

    Returns:
        ``(v_C_next, v_b, s_b)``:
            * ``v_C_next`` — capacitor-sum voltage after ``dt``.
            * ``v_b`` — staircase arm-generated voltage at this step
              (``s_b / N · v_C``).
            * ``s_b`` — integer switching count.

    Notes:
        Use ``dt ≤ 1 / (10 · n_sm · f_carrier)`` to resolve the
        effective switching frequency cleanly. Coarser dt aliases
        the staircase; the running-average v_C trajectory still
        approaches L0 (eq 2.14) as ``dt → 0``.
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")
    r_p_inv = (1.0 / params.r_p) if params.r_p is not None else 0.0
    v_C_next, v_b, s_b_cpp = _cpp_ml_step(
        float(v_C), float(m_ref), float(i_b),
        float(dt), float(t), int(params.n_sm),
        float(params.c_arm), float(params.f_carrier),
        params.sm_type, float(r_p_inv),
    )
    return v_C_next, v_b, int(s_b_cpp)


@dataclass(frozen=True)
class MmcArmMultilevelResult:
    """Output of :func:`simulate_mmc_arm_multilevel`.

    All arrays share the same shape ``(N + 1,)``.

    Attributes:
        t: Time vector [s].
        v_C: Capacitor-sum voltage trajectory [V].
        v_b: Arm-generated staircase voltage trajectory [V].
        m_ref: Applied reference modulation index trajectory.
        s_b: Integer switching-count trajectory (per-step PS-PWM).
        i_b: Arm current trajectory [A].
        params: Parameters used for the run (echoed for traceability).
    """

    t: np.ndarray
    v_C: np.ndarray
    v_b: np.ndarray
    m_ref: np.ndarray
    s_b: np.ndarray
    i_b: np.ndarray
    params: MmcArmMultilevelParams = field(repr=False)


def simulate_mmc_arm_multilevel(
    *,
    duration: float,
    dt: float,
    m_ref: float | Callable[[float], float],
    i_b: float | Callable[[float], float],
    params: MmcArmMultilevelParams,
) -> MmcArmMultilevelResult:
    """Run the L1 multilevel-arm model over ``[0, duration]``.

    Args:
        duration: Simulation length [s] (must be > 0).
        dt: Fixed time step [s] (must be > 0 and ≤ duration). Use
            ``dt ≤ 1 / (10 · n_sm · f_carrier)`` for clean staircase
            resolution.
        m_ref: Reference modulation index. Scalar (constant) or
            callable ``t -> float``.
        i_b: Arm current [A]. Scalar or callable.
        params: Arm configuration.

    Returns:
        A :class:`MmcArmMultilevelResult` carrying the full
        trajectories including the discrete ``s_b`` history.

    Raises:
        ValueError: If ``duration`` or ``dt`` are non-positive, or
            the constant scalar ``m_ref`` lies outside ``[m_min,
            m_max]``. Callable references are clamped at quantize
            time (no exception per-step).
    """
    if duration <= 0:
        raise ValueError(f"duration must be > 0 (got {duration})")
    if dt <= 0 or dt > duration:
        raise ValueError(f"dt must be in (0, duration] (got {dt})")
    if not callable(m_ref):
        m0 = float(m_ref)
        if m0 < params.m_min or m0 > params.m_max:
            raise ValueError(
                f"m_ref={m0:.4f} outside valid range "
                f"[{params.m_min}, {params.m_max}] for "
                f"sm_type={params.sm_type!r}",
            )

    n_steps = int(np.floor(duration / dt))
    n_points = n_steps + 1
    t = np.arange(n_points) * dt

    m_ref_fn = (
        (lambda _t, _v=float(m_ref): _v)
        if not callable(m_ref) else m_ref
    )
    i_b_fn = (
        (lambda _t, _v=float(i_b): _v)
        if not callable(i_b) else i_b
    )

    v_C_arr = np.zeros(n_points)
    v_b_arr = np.zeros(n_points)
    m_ref_arr = np.zeros(n_points)
    s_b_arr = np.zeros(n_points, dtype=np.int64)
    i_b_arr = np.zeros(n_points)

    v_C = float(params.v_c0)
    for k, tk in enumerate(t):
        m_k = float(m_ref_fn(tk))
        i_k = float(i_b_fn(tk))
        s_b_k = ps_pwm_switching_function(
            m_k, tk, params.n_sm, params.f_carrier,
            sm_type=params.sm_type,
        )
        m_b_k = s_b_k / params.n_sm
        m_ref_arr[k] = m_k
        i_b_arr[k] = i_k
        v_C_arr[k] = v_C
        v_b_arr[k] = m_b_k * v_C
        s_b_arr[k] = s_b_k
        if k < n_points - 1:
            leak = (
                (v_C / params.r_p) if params.r_p is not None else 0.0
            )
            dv_dt = (m_b_k * i_k - leak) / params.c_arm
            v_C = v_C + dt * dv_dt

    return MmcArmMultilevelResult(
        t=t,
        v_C=v_C_arr,
        v_b=v_b_arr,
        m_ref=m_ref_arr,
        s_b=s_b_arr,
        i_b=i_b_arr,
        params=params,
    )


# ======================================================================
# L2 — SM-equivalent arm model (dead-time + current-direction routing)
# ======================================================================
#
# Thesis sec 3.4.2 (eqs 3.95–3.99). Adds two pieces of realism on top
# of L1:
#
# 1. **Dead-time** between the complementary switches of every SM.
#    After each PS-PWM edge, the SM enters a free-wheel state (both
#    switches off) for ``t_dead`` seconds. During that window the
#    arm current is routed through one of the SM's body diodes:
#
#       * i_b > 0 ⇒ S2's body diode conducts ⇒ SM is *bypassed*
#         (effective v_SM = 0).
#       * i_b < 0 ⇒ S1's body diode conducts ⇒ SM is *inserted*
#         (effective v_SM = v_C_SM).
#
#    The L0 dynamics then take the form
#
#       m_b_eff(t) = (s_w(t) + s_u(t) · 1[i_b(t) < 0]) / N
#       v_b(t)     = m_b_eff(t) · v_C(t)
#       dv_C/dt    = m_b_eff(t) · i_b(t) / C_arm                 (3.99 simplified)
#
#    where ``s_w`` is the count of fully-inserted SMs (S1 closed) and
#    ``s_u`` is the count of free-wheeling SMs (both switches open).
#
# 2. **Minimum pulse width** ``t_min`` (the IGBT spec). Optional —
#    suppresses any per-SM toggle that would occur within ``t_min``
#    of the previous toggle of the same SM.
#
# The L2 model still carries **one state per arm** (``v_C``) but
# bookkeeps N · {S1 bit, S2 bit, last-toggle time} *internally* so
# the next step can resolve dead-time / min-pulse-width events. We do
# not expose a custom auxiliary-supply load (``p_aux`` in the thesis)
# at this layer — it is a constant-power loss that can be added as a
# parallel resistor ``r_p`` instead.


@dataclass(frozen=True)
class MmcArmEquivalentParams:
    """Configuration for the L2 SM-equivalent arm model.

    Adds dead-time and minimum-pulse-width parameters to L1's set.

    Attributes:
        n_sm: Number of submodules per arm (≥ 1).
        c_sm: Per-SM capacitance [F]. ``C_arm = c_sm / n_sm``.
        sm_type: ``"half_bridge"``. Full-bridge L2 is a follow-up
            (the dead-time bookkeeping doubles per FB SM).
        v_c0: Initial capacitor-sum voltage [V].
        r_p: Optional parallel loss resistance [Ω].
        f_carrier: PS-PWM carrier frequency per SM [Hz].
        t_dead: Dead-time between complementary switches [s]. Set to
            ``0`` to degenerate L2 → L1.
        t_min: Minimum pulse width [s]. Toggles that would happen
            within ``t_min`` of the previous toggle of the same SM
            are suppressed. Default ``0`` (no min-pulse-width).
    """

    n_sm: int
    c_sm: float
    sm_type: SubmoduleType = "half_bridge"
    v_c0: float = 0.0
    r_p: float | None = None
    f_carrier: float = 1000.0
    t_dead: float = 0.0
    t_min: float = 0.0

    def __post_init__(self) -> None:
        if self.n_sm < 1:
            raise ValueError(f"n_sm must be ≥ 1 (got {self.n_sm})")
        if self.c_sm <= 0:
            raise ValueError(f"c_sm must be > 0 (got {self.c_sm})")
        if self.sm_type != "half_bridge":
            raise ValueError(
                f"L2 ships half-bridge only for now "
                f"(got {self.sm_type!r}); full-bridge is a follow-up",
            )
        if self.r_p is not None and self.r_p <= 0:
            raise ValueError(f"r_p must be > 0 when set (got {self.r_p})")
        if self.f_carrier <= 0:
            raise ValueError(
                f"f_carrier must be > 0 (got {self.f_carrier})",
            )
        if self.t_dead < 0:
            raise ValueError(f"t_dead must be ≥ 0 (got {self.t_dead})")
        if self.t_min < 0:
            raise ValueError(f"t_min must be ≥ 0 (got {self.t_min})")

    @property
    def c_arm(self) -> float:
        return self.c_sm / self.n_sm

    @property
    def f_switch(self) -> float:
        return self.n_sm * self.f_carrier

    @property
    def m_min(self) -> float:
        return 0.0

    @property
    def m_max(self) -> float:
        return 1.0


@dataclass
class MmcArmEquivalentState:
    """Mutable per-step state for the L2 arm.

    Internally tracks each SM's two-switch state plus the last-toggle
    time (for min-pulse-width enforcement). Use :func:`make_l2_state`
    to construct a fresh state from a params object.

    Attributes:
        v_C: Arm-equivalent capacitor-sum voltage [V].
        bit_s1: Length-N ``int8`` array — S1 (top switch) on/off per SM.
        bit_s2: Length-N ``int8`` array — S2 (bottom switch) on/off per SM.
        in_dead_time_until: Length-N ``float64`` array — if positive,
            the SM is in dead-time until this absolute time; else
            ``-inf``.
        last_toggle_time: Length-N ``float64`` array — time of the
            *most recent* successful toggle of S1 (for min-pulse-width).
    """

    v_C: float
    bit_s1: np.ndarray
    bit_s2: np.ndarray
    in_dead_time_until: np.ndarray
    last_toggle_time: np.ndarray


def make_l2_state(params: MmcArmEquivalentParams) -> MmcArmEquivalentState:
    """Construct a fresh L2 arm state seeded at ``params.v_c0``.

    All SMs start *bypassed* (S1=0, S2=1) with no pending dead-time.
    """
    n = params.n_sm
    return MmcArmEquivalentState(
        v_C=float(params.v_c0),
        bit_s1=np.zeros(n, dtype=np.int8),
        bit_s2=np.ones(n, dtype=np.int8),
        in_dead_time_until=np.full(n, -np.inf, dtype=np.float64),
        last_toggle_time=np.full(n, -np.inf, dtype=np.float64),
    )


def mmc_arm_equivalent_step(
    state: MmcArmEquivalentState,
    m_ref: float,
    i_b: float,
    dt: float,
    t: float,
    params: MmcArmEquivalentParams,
) -> "tuple[float, int, int]":
    """Advance the L2 SM-equivalent arm by one forward-Euler step.

    Mutates ``state`` in place (advances ``state.v_C`` and the
    per-SM switching arrays). All computation runs in the C++
    kernel (``core/include/pulsim/mmc/arm.hpp``); this wrapper
    forwards the state arrays as numpy buffers.

    Args:
        state: Live L2 state (see :func:`make_l2_state`).
        m_ref: Reference modulation index ``∈ [0, 1]``.
        i_b: Arm current [A] — sign determines free-wheel routing.
        dt: Time step [s] (> 0).
        t: Current time [s].
        params: Arm configuration (dead-time, min-pulse-width, …).

    Returns:
        ``(v_b, s_w, s_u)``:
            * ``v_b`` — arm-generated voltage at this step [V].
            * ``s_w`` — number of "defined inserted" SMs (S1 closed).
            * ``s_u`` — number of free-wheeling SMs (both off).

    Notes:
        ``dt`` must satisfy
        ``dt ≤ min(t_dead, 1/(N·f_carrier)/10)`` to resolve dead-time
        events. Coarser ``dt`` collapses the dead-time effect.
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")

    r_p_inv = (1.0 / params.r_p) if params.r_p is not None else 0.0
    v_C_next, v_b, s_w, s_u = _cpp_eq_step(
        float(state.v_C),
        state.bit_s1, state.bit_s2,
        state.in_dead_time_until, state.last_toggle_time,
        float(m_ref), float(i_b), float(dt), float(t),
        int(params.n_sm), float(params.c_arm),
        float(params.f_carrier),
        float(params.t_dead), float(params.t_min),
        float(r_p_inv),
    )
    state.v_C = v_C_next
    return v_b, int(s_w), int(s_u)


@dataclass(frozen=True)
class MmcArmEquivalentResult:
    """Output of :func:`simulate_mmc_arm_equivalent`."""

    t: np.ndarray
    v_C: np.ndarray
    v_b: np.ndarray
    m_ref: np.ndarray
    s_w: np.ndarray
    s_u: np.ndarray
    i_b: np.ndarray
    params: MmcArmEquivalentParams = field(repr=False)


def simulate_mmc_arm_equivalent(
    *,
    duration: float,
    dt: float,
    m_ref: float | Callable[[float], float],
    i_b: float | Callable[[float], float],
    params: MmcArmEquivalentParams,
) -> MmcArmEquivalentResult:
    """Run the L2 SM-equivalent arm model over ``[0, duration]``.

    Args:
        duration: Simulation length [s] (must be > 0).
        dt: Fixed time step [s]. To resolve dead-time the step must
            be smaller than ``t_dead`` (and the PS-PWM resolution).
        m_ref: Reference modulation index. Scalar or callable.
        i_b: Arm current [A]. Scalar or callable.
        params: Arm configuration.

    Returns:
        :class:`MmcArmEquivalentResult` carrying the full trajectories
        including the running (s_w, s_u) histories.
    """
    if duration <= 0:
        raise ValueError(f"duration must be > 0 (got {duration})")
    if dt <= 0 or dt > duration:
        raise ValueError(f"dt must be in (0, duration] (got {dt})")
    if not callable(m_ref):
        m0 = float(m_ref)
        if m0 < params.m_min or m0 > params.m_max:
            raise ValueError(
                f"m_ref={m0:.4f} outside valid range "
                f"[{params.m_min}, {params.m_max}]",
            )

    m_ref_fn = (
        (lambda _t, _v=float(m_ref): _v)
        if not callable(m_ref) else m_ref
    )
    i_b_fn = (
        (lambda _t, _v=float(i_b): _v)
        if not callable(i_b) else i_b
    )

    n_steps = int(np.floor(duration / dt))
    n_points = n_steps + 1
    t_arr = np.arange(n_points) * dt

    state = make_l2_state(params)

    v_C_arr = np.zeros(n_points)
    v_b_arr = np.zeros(n_points)
    m_ref_arr = np.zeros(n_points)
    s_w_arr = np.zeros(n_points, dtype=np.int64)
    s_u_arr = np.zeros(n_points, dtype=np.int64)
    i_b_arr = np.zeros(n_points)

    for k, tk in enumerate(t_arr):
        m_k = float(m_ref_fn(tk))
        i_k = float(i_b_fn(tk))
        m_ref_arr[k] = m_k
        i_b_arr[k] = i_k
        v_C_arr[k] = state.v_C
        if k < n_points - 1:
            v_b, s_w, s_u = mmc_arm_equivalent_step(
                state, m_k, i_k, dt, float(tk), params,
            )
            v_b_arr[k] = v_b
            s_w_arr[k] = s_w
            s_u_arr[k] = s_u
        else:
            # Compute v_b at the final sample without advancing v_C.
            n = params.n_sm
            s_w = int(state.bit_s1.sum())
            s_u = int(
                ((state.bit_s1 == 0) & (state.bit_s2 == 0)).sum()
            )
            s_eff = s_w + (s_u if i_k < 0 else 0)
            v_b_arr[k] = (s_eff / n) * state.v_C
            s_w_arr[k] = s_w
            s_u_arr[k] = s_u

    return MmcArmEquivalentResult(
        t=t_arr,
        v_C=v_C_arr,
        v_b=v_b_arr,
        m_ref=m_ref_arr,
        s_w=s_w_arr,
        s_u=s_u_arr,
        i_b=i_b_arr,
        params=params,
    )


# ======================================================================
# L3 — Per-SM detailed arm with sort-and-select balancing  Phase 20.7
# ======================================================================
#
# L3 lifts the L0/L1/L2 simplification ``v_C_SM,n ≈ v_C / N`` and
# tracks each SM's capacitor voltage independently. The PS-PWM
# quantizer still picks **how many** SMs to insert (s_b); a
# *balancing algorithm* picks **which** s_b out of the N to insert
# at each step. The classical scheme (Tu / Hu / Xu, 2011) is
# *sort-and-select*:
#
#   * ``i_b ≥ 0`` (charging current): insert the ``s_b`` SMs with the
#     **lowest** ``v_C_n`` so they catch up to the mean.
#   * ``i_b < 0`` (discharging): insert the ``s_b`` SMs with the
#     **highest** ``v_C_n`` so they release energy.
#
# Per-SM dynamics:
#
#   dv_C_n / dt = (insertion_n · i_b − v_C_n / r_p_per_sm) / c_sm   (L3 eq)
#
# where ``insertion_n ∈ {0, 1}`` is whether SM n is in the inserted
# set this step. Summing over all N SMs gives back the L0 / L1
# arm-equivalent dynamics in the limit where all v_C_n are equal:
#
#   d(Σ v_C_n)/dt = (Σ insertion_n · i_b)/c_sm = s_b · i_b / c_sm
#                  = (s_b/N) · i_b / (c_sm/N) = m_b · i_b / C_arm
#
# so L3 is consistent with L0 when balancing keeps the SMs uniform.
#
# We ship two balancing schemes:
#   * ``"sort_and_select"`` — the standard algorithm above.
#   * ``"none"`` — a fixed assignment (first ``s_b`` SMs in index
#     order) that intentionally *does not* balance, useful to see
#     the divergence in tests / showcases.


@dataclass(frozen=True)
class MmcArmDetailedParams:
    """Configuration for the L3 detailed per-SM arm model.

    Attributes:
        n_sm: Number of submodules per arm.
        c_sm: Per-SM capacitance [F].
        sm_type: ``"half_bridge"`` only at this layer.
        v_c0: Initial **arm-sum** voltage [V]; each SM starts at
            ``v_c0 / n_sm``. Pass a heterogeneous initial-state
            array directly via :func:`make_l3_state` if you want
            unbalanced ICs.
        r_p: Optional total arm parallel-loss resistance [Ω]; each
            SM sees an equivalent loss of ``r_p · n_sm`` from its
            own cap so the *arm-sum* discharge rate matches the
            simpler L0/L1/L2 models.
        f_carrier: PS-PWM carrier frequency per SM [Hz].
        balancing: ``"sort_and_select"`` (default) or ``"none"``.
    """

    n_sm: int
    c_sm: float
    sm_type: SubmoduleType = "half_bridge"
    v_c0: float = 0.0
    r_p: float | None = None
    f_carrier: float = 1000.0
    balancing: Literal["sort_and_select", "none"] = "sort_and_select"

    def __post_init__(self) -> None:
        if self.n_sm < 1:
            raise ValueError(f"n_sm must be ≥ 1 (got {self.n_sm})")
        if self.c_sm <= 0:
            raise ValueError(f"c_sm must be > 0 (got {self.c_sm})")
        if self.sm_type != "half_bridge":
            raise ValueError(
                f"L3 ships half-bridge only for now "
                f"(got {self.sm_type!r})",
            )
        if self.r_p is not None and self.r_p <= 0:
            raise ValueError(f"r_p must be > 0 when set (got {self.r_p})")
        if self.f_carrier <= 0:
            raise ValueError(
                f"f_carrier must be > 0 (got {self.f_carrier})",
            )
        if self.balancing not in ("sort_and_select", "none"):
            raise ValueError(
                f"balancing must be 'sort_and_select' or 'none' "
                f"(got {self.balancing!r})",
            )

    @property
    def c_arm(self) -> float:
        """Arm-equivalent capacitance C_arm = c_sm / n_sm [F]."""
        return self.c_sm / self.n_sm

    @property
    def f_switch(self) -> float:
        return self.n_sm * self.f_carrier

    @property
    def m_min(self) -> float:
        return 0.0

    @property
    def m_max(self) -> float:
        return 1.0


@dataclass
class MmcArmDetailedState:
    """Mutable L3 arm state.

    Attributes:
        v_C_per_sm: Length-N ``float64`` array — capacitor voltage
            per submodule [V].
    """

    v_C_per_sm: np.ndarray

    @property
    def v_C(self) -> float:
        """Total arm-sum voltage = Σ v_C_n."""
        return float(self.v_C_per_sm.sum())

    @property
    def v_C_mean(self) -> float:
        """Mean per-SM voltage."""
        return float(self.v_C_per_sm.mean())

    @property
    def v_C_spread(self) -> float:
        """Peak-to-peak per-SM voltage spread (a diagnostic for
        balancing health)."""
        return float(
            self.v_C_per_sm.max() - self.v_C_per_sm.min()
        )


def make_l3_state(
    params: MmcArmDetailedParams,
    *,
    initial_v_C_per_sm: "np.ndarray | None" = None,
) -> MmcArmDetailedState:
    """Construct a fresh L3 arm state.

    Args:
        params: Arm configuration.
        initial_v_C_per_sm: Optional length-``n_sm`` array of per-SM
            initial voltages. Defaults to a uniform distribution
            ``v_c0 / n_sm`` per SM.

    Returns:
        Fresh :class:`MmcArmDetailedState`.
    """
    n = params.n_sm
    if initial_v_C_per_sm is None:
        v = np.full(n, params.v_c0 / n, dtype=np.float64)
    else:
        v = np.asarray(initial_v_C_per_sm, dtype=np.float64)
        if v.shape != (n,):
            raise ValueError(
                f"initial_v_C_per_sm must have shape (n_sm,) = ({n},); "
                f"got {v.shape}",
            )
    return MmcArmDetailedState(v_C_per_sm=v.copy())


def _balance_select(
    v_C_per_sm: np.ndarray,
    s_b: int,
    i_b: float,
    scheme: str,
) -> np.ndarray:
    """Return a boolean mask of length N picking the ``s_b`` SMs to insert.

    Thin numpy-friendly wrapper around the C++
    :func:`pulsim::mmc::balance_select` for visibility in tests
    (the per-step path goes via :func:`mmc_arm_detailed_step` →
    ``_cpp_dt_step``, which calls the same kernel routine).
    """
    n = len(v_C_per_sm)
    if s_b <= 0:
        return np.zeros(n, dtype=bool)
    if s_b >= n:
        return np.ones(n, dtype=bool)
    if scheme == "none":
        mask = np.zeros(n, dtype=bool)
        mask[:s_b] = True
        return mask
    order = np.argsort(v_C_per_sm, kind="stable")
    mask = np.zeros(n, dtype=bool)
    if i_b >= 0:
        mask[order[:s_b]] = True
    else:
        mask[order[-s_b:]] = True
    return mask


def mmc_arm_detailed_step(
    state: MmcArmDetailedState,
    m_ref: float,
    i_b: float,
    dt: float,
    t: float,
    params: MmcArmDetailedParams,
) -> "tuple[float, int, np.ndarray]":
    """Advance the L3 detailed arm by one forward-Euler step.

    Mutates ``state.v_C_per_sm`` in place. All inner-loop math
    (PS-PWM quantizer, sort-and-select balancer, per-SM dynamics)
    runs in the C++ kernel; this wrapper allocates the insertion
    mask buffer and dispatches.

    Args:
        state: Live L3 state (see :func:`make_l3_state`).
        m_ref: Reference modulation index ``∈ [0, 1]``.
        i_b: Arm current [A].
        dt: Time step [s] (> 0).
        t: Current time [s].
        params: Arm configuration.

    Returns:
        ``(v_b, s_b, insertion_mask)``:
            * ``v_b`` — arm-generated voltage = Σ v_C_n for inserted SMs [V].
            * ``s_b`` — count of inserted SMs.
            * ``insertion_mask`` — length-N boolean array of which SMs
              were inserted this step.
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")

    # Per-step scratch — could be cached on `state` if profiling
    # shows it as a hot allocation, but at N ≤ 30 the overhead is
    # negligible compared with the C++ step body.
    insertion = np.zeros(params.n_sm, dtype=np.int8)
    r_p_inv_per_sm = (
        (1.0 / (params.r_p * params.n_sm))
        if params.r_p is not None else 0.0
    )
    v_b, s_b_int = _cpp_dt_step(
        state.v_C_per_sm, insertion,
        float(m_ref), float(i_b), float(dt), float(t),
        int(params.n_sm), float(params.c_sm),
        float(params.f_carrier),
        params.sm_type, params.balancing,
        float(r_p_inv_per_sm),
    )
    return float(v_b), int(s_b_int), insertion.astype(bool)


@dataclass(frozen=True)
class MmcArmDetailedResult:
    """Output of :func:`simulate_mmc_arm_detailed`."""

    t: np.ndarray
    v_C_per_sm: np.ndarray         # shape (n_points, n_sm)
    v_C_sum: np.ndarray            # shape (n_points,)
    v_C_spread: np.ndarray         # shape (n_points,) — pk-pk per step
    v_b: np.ndarray
    m_ref: np.ndarray
    s_b: np.ndarray
    i_b: np.ndarray
    params: MmcArmDetailedParams = field(repr=False)


def simulate_mmc_arm_detailed(
    *,
    duration: float,
    dt: float,
    m_ref: float | Callable[[float], float],
    i_b: float | Callable[[float], float],
    params: MmcArmDetailedParams,
    initial_v_C_per_sm: "np.ndarray | None" = None,
) -> MmcArmDetailedResult:
    """Run the L3 detailed arm model over ``[0, duration]``."""
    if duration <= 0:
        raise ValueError(f"duration must be > 0 (got {duration})")
    if dt <= 0 or dt > duration:
        raise ValueError(f"dt must be in (0, duration] (got {dt})")
    if not callable(m_ref):
        m0 = float(m_ref)
        if m0 < params.m_min or m0 > params.m_max:
            raise ValueError(
                f"m_ref={m0:.4f} outside valid range "
                f"[{params.m_min}, {params.m_max}]",
            )

    m_ref_fn = (
        (lambda _t, _v=float(m_ref): _v)
        if not callable(m_ref) else m_ref
    )
    i_b_fn = (
        (lambda _t, _v=float(i_b): _v)
        if not callable(i_b) else i_b
    )

    state = make_l3_state(params, initial_v_C_per_sm=initial_v_C_per_sm)
    n_steps = int(np.floor(duration / dt))
    n_points = n_steps + 1
    t_arr = np.arange(n_points) * dt

    v_C_per_sm_arr = np.zeros((n_points, params.n_sm))
    v_C_sum_arr = np.zeros(n_points)
    v_C_spread_arr = np.zeros(n_points)
    v_b_arr = np.zeros(n_points)
    m_ref_arr = np.zeros(n_points)
    s_b_arr = np.zeros(n_points, dtype=np.int64)
    i_b_arr = np.zeros(n_points)

    for k, tk in enumerate(t_arr):
        m_k = float(m_ref_fn(tk))
        i_k = float(i_b_fn(tk))
        v_C_per_sm_arr[k] = state.v_C_per_sm
        v_C_sum_arr[k] = state.v_C
        v_C_spread_arr[k] = state.v_C_spread
        m_ref_arr[k] = m_k
        i_b_arr[k] = i_k
        if k < n_points - 1:
            v_b, s_b, _ = mmc_arm_detailed_step(
                state, m_k, i_k, dt, float(tk), params,
            )
            v_b_arr[k] = v_b
            s_b_arr[k] = s_b
        else:
            # Compute v_b at the final sample without advancing state.
            s_b_final = ps_pwm_switching_function(
                m_k, float(tk), params.n_sm, params.f_carrier,
                sm_type=params.sm_type,
            )
            insertion = _balance_select(
                state.v_C_per_sm, s_b_final, i_k, params.balancing,
            )
            v_b_arr[k] = float(state.v_C_per_sm[insertion].sum())
            s_b_arr[k] = s_b_final

    return MmcArmDetailedResult(
        t=t_arr,
        v_C_per_sm=v_C_per_sm_arr,
        v_C_sum=v_C_sum_arr,
        v_C_spread=v_C_spread_arr,
        v_b=v_b_arr,
        m_ref=m_ref_arr,
        s_b=s_b_arr,
        i_b=i_b_arr,
        params=params,
    )


# ======================================================================
# Builder-integration for L1/L2/L3  Phase 20.8
# ======================================================================
#
# Same pattern as ``add_mmc_arm_average`` / ``make_mmc_arms_observer``:
# the kernel sees a single voltage source per arm whose value is
# updated each simulation step by the observer / b_extra_fn pair.
# The L1/L2/L3 dynamics (PS-PWM quantizer, dead-time state machine,
# per-SM balancing) live in Python — they are exercised once per
# kernel step via the layer's ``mmc_arm_*_step`` function.
#
# Sign conventions (validated empirically in Phase 20.4):
#   * V-source ``x[src_idx]`` is positive when current flows
#     ``from → to`` internally.
#   * That matches the physical ``i_b`` direction (current entering
#     the arm at ``node_a`` charges the cap when modulation is
#     positive) — **no sign negation** is needed in the observer.
#
# DC-OP seeding:
#   * Set the v-source baseline to ``m_ref(0) · v_c0`` so DC OP
#     finds a consistent operating point in multi-arm topologies.
#   * b_extra_fn injects the *delta* from baseline: at every step,
#     ``inject(t) = baseline - v_b(t)`` so the effective source
#     voltage is ``v_b(t)`` (matches the kernel convention
#     ``V_source_effective = baseline - inject``).


# ----------------------------------------------------------------------
# L1 — Multilevel arm builder helper
# ----------------------------------------------------------------------

@dataclass
class MmcArmMultilevel:
    """Builder-side wrapper for an L1 multilevel arm.

    Mirrors :class:`MmcArmAverage` but references the L1 step. The
    runtime state is just ``v_C`` (one per arm); per-SM PS-PWM bits
    are recomputed each step from ``t`` and the carrier phase.

    Attributes:
        params: Static configuration.
        m_ref_fn: Reference modulation signal ``t -> m_ref``.
        v_C: Live arm-equivalent capacitor-sum voltage [V].
        v_b: Stashed arm-generated voltage for the next b_extra call.
        v_b_baseline: V-source baseline (m_ref(0)·v_c0) for DC-OP.
        name: Prefix used for the underlying source name.
        source_branch_id: Graph branch id of the v-source.
    """

    params: MmcArmMultilevelParams
    m_ref_fn: Callable[[float], float]
    v_C: float = 0.0
    v_b: float = 0.0
    v_b_baseline: float = 0.0
    name: str = ""
    source_branch_id: int = -1


def add_mmc_arm_multilevel(
    builder,
    *,
    name: str,
    node_a: str,
    node_b: str,
    params: MmcArmMultilevelParams,
    m_ref: float | Callable[[float], float],
) -> MmcArmMultilevel:
    """Add an L1 multilevel-arm to ``builder``.

    Pair the returned object with :func:`make_mmc_arm_multilevel_observer`
    to drive the dynamics each simulation step.
    """
    if callable(m_ref):
        m_ref_fn = m_ref
    else:
        m_ref_const = float(m_ref)
        m_ref_fn = lambda _t, _v=m_ref_const: _v  # noqa: E731

    m0 = float(m_ref_fn(0.0))
    if m0 < params.m_min or m0 > params.m_max:
        raise ValueError(
            f"m_ref(t=0)={m0:.4f} outside valid range "
            f"[{params.m_min}, {params.m_max}] for "
            f"sm_type={params.sm_type!r}",
        )

    v_b_baseline = m0 * float(params.v_c0)
    src_id = builder.graph.num_branches
    builder.add_voltage_source(
        f"{name}_Varm", node_a, node_b, v_b_baseline,
    )

    return MmcArmMultilevel(
        params=params,
        m_ref_fn=m_ref_fn,
        v_C=float(params.v_c0),
        v_b=v_b_baseline,
        v_b_baseline=v_b_baseline,
        name=name,
        source_branch_id=src_id,
    )


def make_mmc_arm_multilevel_observer(
    builder, arm: MmcArmMultilevel, *, dt: float,
):
    """Single-arm wrapper around
    :func:`make_mmc_arm_multilevel_observers`."""
    return make_mmc_arm_multilevel_observers(builder, [arm], dt=dt)


def make_mmc_arm_multilevel_observers(
    builder, arms: "list[MmcArmMultilevel]", *, dt: float,
):
    """Build ``(step_observer, b_extra_fn)`` for one or more L1 arms.

    Notes:
        Use ``dt ≤ 1 / (10 · N · f_carrier)`` so the per-step
        observer sees a clean staircase. With ``start_from_dc_op=True``
        the trajectory has the same ~+1·dt boundary bias L0 carries
        (the observer fires N+1 times for N integration steps).
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")
    if not arms:
        raise ValueError("arms must contain at least one element")

    state_size = builder.pool.state_size(builder.graph)
    src_indices = [
        builder.pool.branch_var_id_for_source(
            arm.source_branch_id, builder.graph,
        )
        for arm in arms
    ]

    def step_observer(t, x):
        for k, arm in enumerate(arms):
            i_b = float(x[src_indices[k]])
            m_k = float(arm.m_ref_fn(t))
            v_C_next, _, _s_b = mmc_arm_multilevel_step(
                arm.v_C, m_k, i_b, dt, t, arm.params,
            )
            arm.v_C = v_C_next
            # Stash next-step v_b using the s_b evaluated at t+dt
            # so b_extra_fn injects the correct staircase value.
            t_next = t + dt
            s_b_next = ps_pwm_switching_function(
                float(arm.m_ref_fn(t_next)), t_next,
                arm.params.n_sm, arm.params.f_carrier,
                sm_type=arm.params.sm_type,
            )
            arm.v_b = (s_b_next / arm.params.n_sm) * v_C_next

    def b_extra_fn(_t):
        out = [0.0] * state_size
        for k, arm in enumerate(arms):
            out[src_indices[k]] = arm.v_b_baseline - arm.v_b
        return out

    return step_observer, b_extra_fn


# ----------------------------------------------------------------------
# L2 — SM-equivalent arm builder helper
# ----------------------------------------------------------------------

@dataclass
class MmcArmEquivalent:
    """Builder-side wrapper for an L2 SM-equivalent arm.

    Owns its own :class:`MmcArmEquivalentState` (per-SM bits +
    dead-time timers); the observer advances both ``state.v_C``
    and the per-SM bookkeeping each step.

    Attributes:
        params: Static configuration.
        m_ref_fn: Reference modulation signal ``t -> m_ref``.
        state: Live L2 state (per-SM bits + timers + v_C).
        v_b: Last computed arm voltage (stashed for next b_extra).
        v_b_baseline: V-source baseline for DC-OP.
        name: Prefix for the underlying source name.
        source_branch_id: Graph branch id of the v-source.
    """

    params: MmcArmEquivalentParams
    m_ref_fn: Callable[[float], float]
    state: MmcArmEquivalentState
    v_b: float = 0.0
    v_b_baseline: float = 0.0
    name: str = ""
    source_branch_id: int = -1

    @property
    def v_C(self) -> float:
        """Arm-sum capacitor voltage (delegates to the internal state)."""
        return self.state.v_C


def add_mmc_arm_equivalent(
    builder,
    *,
    name: str,
    node_a: str,
    node_b: str,
    params: MmcArmEquivalentParams,
    m_ref: float | Callable[[float], float],
) -> MmcArmEquivalent:
    """Add an L2 SM-equivalent arm to ``builder``."""
    if callable(m_ref):
        m_ref_fn = m_ref
    else:
        m_ref_const = float(m_ref)
        m_ref_fn = lambda _t, _v=m_ref_const: _v  # noqa: E731

    m0 = float(m_ref_fn(0.0))
    if m0 < params.m_min or m0 > params.m_max:
        raise ValueError(
            f"m_ref(t=0)={m0:.4f} outside valid range "
            f"[{params.m_min}, {params.m_max}]",
        )

    v_b_baseline = m0 * float(params.v_c0)
    src_id = builder.graph.num_branches
    builder.add_voltage_source(
        f"{name}_Varm", node_a, node_b, v_b_baseline,
    )

    return MmcArmEquivalent(
        params=params,
        m_ref_fn=m_ref_fn,
        state=make_l2_state(params),
        v_b=v_b_baseline,
        v_b_baseline=v_b_baseline,
        name=name,
        source_branch_id=src_id,
    )


def make_mmc_arm_equivalent_observer(
    builder, arm: MmcArmEquivalent, *, dt: float,
):
    return make_mmc_arm_equivalent_observers(builder, [arm], dt=dt)


def make_mmc_arm_equivalent_observers(
    builder, arms: "list[MmcArmEquivalent]", *, dt: float,
):
    """Build ``(step_observer, b_extra_fn)`` for one or more L2 arms.

    Notes:
        L2 has a per-SM state machine that advances inside
        ``mmc_arm_equivalent_step``. ``arm.v_b`` is stashed from the
        v_b returned by the *current* step — there is a 1-dt lag
        between the v_b the kernel injects and the v_b that
        corresponds to the *advanced* state. Acceptable at L2's
        target step sizes (well below 1/f_switch).

        ``dt`` must satisfy ``dt < t_dead`` to resolve dead-time
        events, and ``dt ≤ 1 / (20 · N · f_carrier)`` for the
        PS-PWM staircase.
    """
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")
    if not arms:
        raise ValueError("arms must contain at least one element")

    state_size = builder.pool.state_size(builder.graph)
    src_indices = [
        builder.pool.branch_var_id_for_source(
            arm.source_branch_id, builder.graph,
        )
        for arm in arms
    ]

    def step_observer(t, x):
        for k, arm in enumerate(arms):
            i_b = float(x[src_indices[k]])
            m_k = float(arm.m_ref_fn(t))
            v_b, _s_w, _s_u = mmc_arm_equivalent_step(
                arm.state, m_k, i_b, dt, t, arm.params,
            )
            # Stash the v_b just computed for the next b_extra call.
            arm.v_b = v_b

    def b_extra_fn(_t):
        out = [0.0] * state_size
        for k, arm in enumerate(arms):
            out[src_indices[k]] = arm.v_b_baseline - arm.v_b
        return out

    return step_observer, b_extra_fn


# ----------------------------------------------------------------------
# L3 — Detailed per-SM arm builder helper
# ----------------------------------------------------------------------

@dataclass
class MmcArmDetailed:
    """Builder-side wrapper for an L3 detailed per-SM arm.

    Owns an :class:`MmcArmDetailedState` so the observer can advance
    the per-SM capacitor voltages each step under the configured
    balancing scheme.

    Attributes:
        params: Static configuration (includes ``balancing``).
        m_ref_fn: Reference modulation signal.
        state: Live L3 state (per-SM v_C array).
        v_b: Last computed arm voltage stash.
        v_b_baseline: V-source DC-OP baseline.
        name: Source-name prefix.
        source_branch_id: Graph branch id.
    """

    params: MmcArmDetailedParams
    m_ref_fn: Callable[[float], float]
    state: MmcArmDetailedState
    v_b: float = 0.0
    v_b_baseline: float = 0.0
    name: str = ""
    source_branch_id: int = -1

    @property
    def v_C(self) -> float:
        """Arm-sum capacitor voltage (Σ v_C_n)."""
        return self.state.v_C

    @property
    def v_C_spread(self) -> float:
        """Per-SM peak-to-peak spread (balancing diagnostic)."""
        return self.state.v_C_spread


def add_mmc_arm_detailed(
    builder,
    *,
    name: str,
    node_a: str,
    node_b: str,
    params: MmcArmDetailedParams,
    m_ref: float | Callable[[float], float],
    initial_v_C_per_sm: "np.ndarray | None" = None,
) -> MmcArmDetailed:
    """Add an L3 detailed arm to ``builder``."""
    if callable(m_ref):
        m_ref_fn = m_ref
    else:
        m_ref_const = float(m_ref)
        m_ref_fn = lambda _t, _v=m_ref_const: _v  # noqa: E731

    m0 = float(m_ref_fn(0.0))
    if m0 < params.m_min or m0 > params.m_max:
        raise ValueError(
            f"m_ref(t=0)={m0:.4f} outside valid range "
            f"[{params.m_min}, {params.m_max}]",
        )

    v_b_baseline = m0 * float(params.v_c0)
    src_id = builder.graph.num_branches
    builder.add_voltage_source(
        f"{name}_Varm", node_a, node_b, v_b_baseline,
    )

    return MmcArmDetailed(
        params=params,
        m_ref_fn=m_ref_fn,
        state=make_l3_state(
            params, initial_v_C_per_sm=initial_v_C_per_sm,
        ),
        v_b=v_b_baseline,
        v_b_baseline=v_b_baseline,
        name=name,
        source_branch_id=src_id,
    )


def make_mmc_arm_detailed_observer(
    builder, arm: MmcArmDetailed, *, dt: float,
):
    return make_mmc_arm_detailed_observers(builder, [arm], dt=dt)


def make_mmc_arm_detailed_observers(
    builder, arms: "list[MmcArmDetailed]", *, dt: float,
):
    """Build ``(step_observer, b_extra_fn)`` for one or more L3 arms."""
    if dt <= 0:
        raise ValueError(f"dt must be > 0 (got {dt})")
    if not arms:
        raise ValueError("arms must contain at least one element")

    state_size = builder.pool.state_size(builder.graph)
    src_indices = [
        builder.pool.branch_var_id_for_source(
            arm.source_branch_id, builder.graph,
        )
        for arm in arms
    ]

    def step_observer(t, x):
        for k, arm in enumerate(arms):
            i_b = float(x[src_indices[k]])
            m_k = float(arm.m_ref_fn(t))
            v_b, _s_b, _mask = mmc_arm_detailed_step(
                arm.state, m_k, i_b, dt, t, arm.params,
            )
            arm.v_b = v_b

    def b_extra_fn(_t):
        out = [0.0] * state_size
        for k, arm in enumerate(arms):
            out[src_indices[k]] = arm.v_b_baseline - arm.v_b
        return out

    return step_observer, b_extra_fn
