"""Validation tests for the L1 MMC multilevel-arm model.

L1 replaces L0's continuous ``m_b`` with a quantized ``s_b ∈ {0..N}``
generated by phase-shifted PWM. The dynamics are mathematically
identical (eqs 2.9 ≡ 2.14 with m_b ≡ s_b/N); the only new physics is
the staircase ``v_b(t)`` and the high-frequency switching ripple it
puts on top of the L0 envelope.

What we verify:

  * **Quantizer range.** s_b ∈ {0..N} for HB, {-N..N} for FB, for any
    m_ref (out-of-range inputs are silently clamped).
  * **Time-averaged duty.** Over one carrier period, the average of
    s_b/N tracks the constant m_ref within one bit.
  * **Multilevel output.** v_b takes at most N+1 distinct levels and
    each level appears at least once for a representative sweep.
  * **Effective switching frequency.** The number of s_b transitions
    per carrier period equals 2N for HB (each of N carriers fires a
    rising and a falling edge per period).
  * **L1 → L0 envelope convergence.** Low-pass-filter L1's v_b at a
    cutoff well below ``f_carrier`` and confirm it tracks L0's v_b
    (continuous-m_b case) within < 2 % at the same m_ref.
  * **Parameter contract guard rails.**
"""

from __future__ import annotations

import numpy as np
import pytest

from pulsim.mmc import (
    MmcArmAverageParams,
    MmcArmMultilevelParams,
    MmcArmMultilevelResult,
    mmc_arm_multilevel_step,
    ps_pwm_switching_function,
    simulate_mmc_arm_average,
    simulate_mmc_arm_multilevel,
)


# ---------------------------------------------------------------------------
# Parameter contract
# ---------------------------------------------------------------------------

class TestParams:
    def test_defaults(self):
        p = MmcArmMultilevelParams(n_sm=8, c_sm=1e-3)
        assert p.n_sm == 8
        assert p.c_sm == 1e-3
        assert p.sm_type == "half_bridge"
        assert p.v_c0 == 0.0
        assert p.r_p is None
        assert p.f_carrier == 1000.0
        assert p.c_arm == pytest.approx(1.25e-4)
        assert p.f_switch == pytest.approx(8000.0)
        assert p.m_min == 0.0
        assert p.m_max == 1.0

    def test_full_bridge(self):
        p = MmcArmMultilevelParams(
            n_sm=4, c_sm=1e-3, sm_type="full_bridge", f_carrier=2000.0,
        )
        assert p.m_min == -1.0
        assert p.m_max == 1.0
        assert p.f_switch == 8000.0

    def test_reject_zero_n_sm(self):
        with pytest.raises(ValueError, match="n_sm"):
            MmcArmMultilevelParams(n_sm=0, c_sm=1e-3)

    def test_reject_non_positive_c_sm(self):
        with pytest.raises(ValueError, match="c_sm"):
            MmcArmMultilevelParams(n_sm=4, c_sm=-1e-6)

    def test_reject_unknown_sm_type(self):
        with pytest.raises(ValueError, match="sm_type"):
            MmcArmMultilevelParams(  # type: ignore[arg-type]
                n_sm=4, c_sm=1e-3, sm_type="quarter",
            )

    def test_reject_non_positive_r_p(self):
        with pytest.raises(ValueError, match="r_p"):
            MmcArmMultilevelParams(n_sm=4, c_sm=1e-3, r_p=0.0)

    def test_reject_non_positive_f_carrier(self):
        with pytest.raises(ValueError, match="f_carrier"):
            MmcArmMultilevelParams(n_sm=4, c_sm=1e-3, f_carrier=0.0)


# ---------------------------------------------------------------------------
# PS-PWM switching function
# ---------------------------------------------------------------------------

class TestQuantizer:
    """Direct tests of ps_pwm_switching_function()."""

    @pytest.mark.parametrize("n_sm", [1, 4, 10, 30])
    def test_hb_range(self, n_sm):
        """HB s_b ∈ {0..N} for any t and m_ref ∈ [0, 1]."""
        for m_ref in [0.0, 0.1, 0.5, 0.9, 1.0]:
            for t in np.linspace(0.0, 1e-3, 27):
                s = ps_pwm_switching_function(
                    m_ref, float(t), n_sm, 1000.0,
                    sm_type="half_bridge",
                )
                assert 0 <= s <= n_sm, (
                    f"HB s_b={s} out of range [0,{n_sm}] "
                    f"at t={t}, m={m_ref}"
                )

    @pytest.mark.parametrize("n_sm", [1, 4, 10])
    def test_fb_range(self, n_sm):
        """FB s_b ∈ {-N..N} with sign tracking m_ref."""
        for m_ref in [-1.0, -0.5, 0.0, 0.3, 1.0]:
            for t in np.linspace(0.0, 1e-3, 27):
                s = ps_pwm_switching_function(
                    m_ref, float(t), n_sm, 1000.0,
                    sm_type="full_bridge",
                )
                assert -n_sm <= s <= n_sm
                if m_ref > 0:
                    assert s >= 0
                elif m_ref < 0:
                    assert s <= 0

    def test_clamps_out_of_range_silently(self):
        """Out-of-range m_ref is clamped — no exception (hot loop)."""
        # HB clamps to [0, 1].
        # Below-range → 0 fires (m clamped to 0, strict m > tri is
        # always false at tri ≥ 0).
        assert ps_pwm_switching_function(
            -0.5, 0.0, 4, 1000.0, sm_type="half_bridge",
        ) == 0
        # Above-range → all SMs fire EXCEPT any carrier that happens
        # to sit at the peak (tri = 1.0) at the sampled instant (m > 1.0
        # is false when m clamps to 1.0). Off the peak, all N fire.
        # Use a non-singular time to get the clean N-bit result:
        n = 8
        assert ps_pwm_switching_function(
            2.0, 1e-7, n, 1000.0, sm_type="half_bridge",
        ) == n

    def test_time_averaged_duty_tracks_m_ref(self):
        """Over one carrier period, mean(s_b)/N should equal m_ref
        within one bit (= 1/N)."""
        n_sm = 10
        f = 1000.0
        T = 1.0 / f
        for m_ref in [0.1, 0.3, 0.5, 0.7, 0.9]:
            ts = np.linspace(0.0, T, 1001, endpoint=False)
            s_values = [
                ps_pwm_switching_function(
                    m_ref, float(t), n_sm, f, sm_type="half_bridge",
                )
                for t in ts
            ]
            mean = float(np.mean(s_values)) / n_sm
            # One-bit tolerance plus a small numerical margin for
            # the finite-sample average.
            assert abs(mean - m_ref) <= 1.0 / n_sm + 1e-3, (
                f"m_ref={m_ref}: mean(s_b)/N = {mean:.4f}"
            )

    def test_n_levels_observed_equals_n_plus_1(self):
        """Sweeping m_ref over [0, 1] visits every level 0..N."""
        n_sm = 8
        f = 1000.0
        T = 1.0 / f
        seen: set[int] = set()
        for m_ref in np.linspace(0.0, 1.0, 51):
            for t in np.linspace(0.0, T, 101, endpoint=False):
                s = ps_pwm_switching_function(
                    float(m_ref), float(t), n_sm, f,
                    sm_type="half_bridge",
                )
                seen.add(s)
        assert seen == set(range(n_sm + 1))

    def test_constant_m_ref_periodic_in_carrier(self):
        """Constant m_ref ⇒ s_b(t) is periodic with period 1/f."""
        n_sm = 6
        f = 5000.0
        T = 1.0 / f
        m_ref = 0.45
        # Sample s_b at t and t+T; should agree.
        for t0 in np.linspace(0.0, 1e-3, 17):
            s1 = ps_pwm_switching_function(
                m_ref, float(t0), n_sm, f, sm_type="half_bridge",
            )
            s2 = ps_pwm_switching_function(
                m_ref, float(t0 + T), n_sm, f, sm_type="half_bridge",
            )
            assert s1 == s2


# ---------------------------------------------------------------------------
# Step + driver
# ---------------------------------------------------------------------------

class TestStep:
    def test_reject_non_positive_dt(self):
        params = MmcArmMultilevelParams(n_sm=4, c_sm=1e-3)
        with pytest.raises(ValueError, match="dt"):
            mmc_arm_multilevel_step(0.0, 0.5, 1.0, 0.0, 0.0, params)

    def test_v_b_quantized(self):
        """v_b == (s_b / N) · v_C — never anything in between."""
        params = MmcArmMultilevelParams(
            n_sm=4, c_sm=1e-3, f_carrier=1000.0,
        )
        for t in np.linspace(0.0, 1e-3, 31):
            v_C_next, v_b, s_b = mmc_arm_multilevel_step(
                v_C=100.0, m_ref=0.45, i_b=0.0,
                dt=1e-5, t=float(t), params=params,
            )
            assert v_b == pytest.approx((s_b / params.n_sm) * 100.0)


class TestSimulate:
    def test_result_shape(self):
        params = MmcArmMultilevelParams(
            n_sm=8, c_sm=1e-3, v_c0=400.0, f_carrier=1000.0,
        )
        # dt small enough to resolve switching: 1 / (10·N·f) = 12.5 µs
        # → use 5 µs.
        res = simulate_mmc_arm_multilevel(
            duration=1e-3, dt=5e-6,
            m_ref=0.5, i_b=0.0,
            params=params,
        )
        assert isinstance(res, MmcArmMultilevelResult)
        assert res.t.shape == (201,)
        for arr in (res.v_C, res.v_b, res.m_ref, res.s_b, res.i_b):
            assert arr.shape == (201,)
        # s_b is integer-valued.
        assert res.s_b.dtype.kind == "i"
        assert res.params is params

    def test_zero_current_keeps_v_C(self):
        """Even with switching, i_b=0 ⇒ no v_C drift."""
        params = MmcArmMultilevelParams(
            n_sm=8, c_sm=1e-3, v_c0=600.0, f_carrier=1000.0,
        )
        res = simulate_mmc_arm_multilevel(
            duration=2e-3, dt=5e-6,
            m_ref=0.5, i_b=0.0,
            params=params,
        )
        assert np.allclose(res.v_C, 600.0)
        # v_b is a staircase between 0..v_C in N+1 steps.
        unique_levels = set(np.unique(res.v_b))
        # Expected discrete levels: (s_b / N) · 600 for s_b ∈ {0..N}.
        # We don't expect *every* level to appear with constant m=0.5
        # (the PS-PWM only visits adjacent levels around s_b ≈ 4),
        # but every observed level should be exactly s_b/8 · 600.
        for v in unique_levels:
            ratio = v / 600.0
            s_b_eff = ratio * params.n_sm
            assert s_b_eff == pytest.approx(round(s_b_eff), abs=1e-12), (
                f"v_b={v} is not a clean s_b/N·v_C level"
            )

    def test_dc_charging_matches_time_averaged_l0(self):
        """Time-averaged L1 v_C trajectory should track L0 (continuous
        m_b) under a constant reference and constant current."""
        n_sm = 10
        c_sm = 2e-3
        v_c0 = 500.0
        m = 0.5
        i_const = 4.0
        f_carrier = 2000.0
        # dt < 1 / (10·N·f) = 5 µs
        dt = 1e-6
        duration = 2e-3

        params_l1 = MmcArmMultilevelParams(
            n_sm=n_sm, c_sm=c_sm, v_c0=v_c0, f_carrier=f_carrier,
        )
        params_l0 = MmcArmAverageParams(
            n_sm=n_sm, c_sm=c_sm, v_c0=v_c0,
        )
        res_l1 = simulate_mmc_arm_multilevel(
            duration=duration, dt=dt, m_ref=m, i_b=i_const,
            params=params_l1,
        )
        res_l0 = simulate_mmc_arm_average(
            duration=duration, dt=dt, m_b=m, i_b=i_const,
            params=params_l0,
        )

        # Final v_C agreement: L1 charges at the *time-averaged*
        # m_b = m_ref, so its final v_C should match L0 within one
        # bit of resolution (= dt · 1/N · i_const / C_arm per step).
        # Over 2000 steps the accumulated PWM ripple stays bounded
        # at < 1 % of the swing.
        swing = res_l0.v_C[-1] - v_c0
        diff = abs(res_l1.v_C[-1] - res_l0.v_C[-1])
        assert diff <= 0.01 * abs(swing) + 0.5, (
            f"L1 final v_C = {res_l1.v_C[-1]:.4f} differs by "
            f"{diff:.4f} from L0 ({res_l0.v_C[-1]:.4f}); swing was "
            f"{swing:.4f}"
        )

    def test_switching_frequency_at_arm_output(self):
        """v_b transitions per second ≈ 2 · N · f_carrier (each
        carrier fires one rising + one falling edge per carrier
        period). Use m_ref ≠ 0.5 to avoid the EVEN-N degenerate
        case where every rising crossing is paired with a falling
        crossing at the same instant (s_b stays locked at N/2)."""
        n_sm = 6
        f_carrier = 1000.0
        # Resolve the effective switching frequency with margin:
        # dt = 1 / (20 · N · f) = 8.3 µs.
        dt = 5e-6
        duration = 10e-3  # ten carrier periods
        params = MmcArmMultilevelParams(
            n_sm=n_sm, c_sm=1e-3, v_c0=100.0, f_carrier=f_carrier,
        )
        res = simulate_mmc_arm_multilevel(
            duration=duration, dt=dt, m_ref=0.45, i_b=0.0,
            params=params,
        )
        # Count transitions in s_b.
        transitions = int(np.sum(np.diff(res.s_b) != 0))
        # Expected transitions in `duration` = 2·N·f·duration.
        expected = 2 * n_sm * f_carrier * duration
        # ±10 % to absorb sampling-grid quantization (some transitions
        # land in the same dt bucket).
        assert transitions == pytest.approx(expected, rel=0.10), (
            f"transitions={transitions}, expected {expected}"
        )

    def test_m_ref_half_with_even_n_locks_s_b(self):
        """Documented PS-PWM quirk: m_ref = 0.5 with even N produces
        a constant s_b = N/2 because every rising crossing of a
        carrier coincides with a falling crossing of its 180°-shifted
        sibling. Useful sanity check that our implementation
        reproduces this analytical property."""
        n_sm = 6
        params = MmcArmMultilevelParams(
            n_sm=n_sm, c_sm=1e-3, v_c0=100.0, f_carrier=1000.0,
        )
        res = simulate_mmc_arm_multilevel(
            duration=5e-3, dt=5e-6, m_ref=0.5, i_b=0.0,
            params=params,
        )
        # s_b should be N/2 = 3 almost everywhere; a couple of
        # samples drop to 2 due to floating-point timing of paired
        # crossings, but those excursions are < 5 % of samples.
        n_off = int(np.sum(res.s_b != n_sm // 2))
        assert n_off < 0.05 * len(res.s_b), (
            f"PS-PWM m=0.5 should lock at N/2; saw {n_off} off-level "
            f"samples out of {len(res.s_b)}"
        )

    def test_reject_invalid_durations(self):
        params = MmcArmMultilevelParams(n_sm=4, c_sm=1e-3)
        with pytest.raises(ValueError, match="duration"):
            simulate_mmc_arm_multilevel(
                duration=0.0, dt=1e-5, m_ref=0.0, i_b=0.0,
                params=params,
            )
        with pytest.raises(ValueError, match="dt"):
            simulate_mmc_arm_multilevel(
                duration=1e-3, dt=2e-3, m_ref=0.0, i_b=0.0,
                params=params,
            )

    def test_reject_const_m_ref_out_of_range(self):
        """Scalar m_ref outside [m_min, m_max] raises at build time."""
        params = MmcArmMultilevelParams(n_sm=4, c_sm=1e-3)
        with pytest.raises(ValueError, match="outside valid range"):
            simulate_mmc_arm_multilevel(
                duration=1e-3, dt=1e-5, m_ref=-0.1, i_b=0.0,
                params=params,
            )

    def test_full_bridge_negative_modulation(self):
        """FB with negative m_ref produces negative s_b and negative v_b."""
        params = MmcArmMultilevelParams(
            n_sm=4, c_sm=1e-3, sm_type="full_bridge",
            v_c0=400.0, f_carrier=1000.0,
        )
        res = simulate_mmc_arm_multilevel(
            duration=1e-3, dt=5e-6, m_ref=-0.5, i_b=0.0,
            params=params,
        )
        # All s_b values should be ≤ 0 for m_ref < 0.
        assert (res.s_b <= 0).all()
        assert (res.s_b >= -params.n_sm).all()
        # v_b ≤ 0 (m_ref < 0 ⇒ v_b = (negative s_b/N) · v_C).
        assert (res.v_b <= 0).all()
