add_test( [==[YAML loader: voltage_source round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: voltage_source round-trip]==]  )
set_tests_properties( [==[YAML loader: voltage_source round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: pwm_voltage_source round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: pwm_voltage_source round-trip]==]  )
set_tests_properties( [==[YAML loader: pwm_voltage_source round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: sine_voltage_source round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: sine_voltage_source round-trip]==]  )
set_tests_properties( [==[YAML loader: sine_voltage_source round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: mosfet_level1 round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: mosfet_level1 round-trip]==]  )
set_tests_properties( [==[YAML loader: mosfet_level1 round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: pulse_voltage_source round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: pulse_voltage_source round-trip]==]  )
set_tests_properties( [==[YAML loader: pulse_voltage_source round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: current_source round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: current_source round-trip]==]  )
set_tests_properties( [==[YAML loader: current_source round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: resistor round-trip (R in ohms → G = 1/R)]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: resistor round-trip (R in ohms → G = 1/R)]==]  )
set_tests_properties( [==[YAML loader: resistor round-trip (R in ohms → G = 1/R)]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: capacitor round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: capacitor round-trip]==]  )
set_tests_properties( [==[YAML loader: capacitor round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: inductor round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: inductor round-trip]==]  )
set_tests_properties( [==[YAML loader: inductor round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: diode round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: diode round-trip]==]  )
set_tests_properties( [==[YAML loader: diode round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: nonlinear_diode round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: nonlinear_diode round-trip]==]  )
set_tests_properties( [==[YAML loader: nonlinear_diode round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: mosfet round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: mosfet round-trip]==]  )
set_tests_properties( [==[YAML loader: mosfet round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: mosfet_with_body_diode adds 2 branches]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: mosfet_with_body_diode adds 2 branches]==]  )
set_tests_properties( [==[YAML loader: mosfet_with_body_diode adds 2 branches]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: igbt round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: igbt round-trip]==]  )
set_tests_properties( [==[YAML loader: igbt round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: transformer round-trip]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: transformer round-trip]==]  )
set_tests_properties( [==[YAML loader: transformer round-trip]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: simulation: block populates SimulationOptions]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: simulation: block populates SimulationOptions]==]  )
set_tests_properties( [==[YAML loader: simulation: block populates SimulationOptions]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: missing R on resistor throws with name]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: missing R on resistor throws with name]==]  )
set_tests_properties( [==[YAML loader: missing R on resistor throws with name]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: unknown device type throws with the type name]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: unknown device type throws with the type name]==]  )
set_tests_properties( [==[YAML loader: unknown device type throws with the type name]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: missing top-level circuit: throws]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: missing top-level circuit: throws]==]  )
set_tests_properties( [==[YAML loader: missing top-level circuit: throws]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML-built half-wave rectifier matches direct builder]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML-built half-wave rectifier matches direct builder]==]  )
set_tests_properties( [==[YAML-built half-wave rectifier matches direct builder]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML-built V_dc + R: DC solve gives v_node = V_dc]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML-built V_dc + R: DC solve gives v_node = V_dc]==]  )
set_tests_properties( [==[YAML-built V_dc + R: DC solve gives v_node = V_dc]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: malformed YAML throws cleanly]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: malformed YAML throws cleanly]==]  )
set_tests_properties( [==[YAML loader: malformed YAML throws cleanly]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
add_test( [==[YAML loader: simulation.store_every is honoured, not ignored]==] /Users/lgili/pulsim_phase2/build-tests/core/pulsim_core_yaml_tests [==[YAML loader: simulation.store_every is honoured\, not ignored]==]  )
set_tests_properties( [==[YAML loader: simulation.store_every is honoured, not ignored]==] PROPERTIES WORKING_DIRECTORY /Users/lgili/pulsim_phase2/build-tests/core SKIP_RETURN_CODE 4)
set( pulsim_core_yaml_tests_TESTS [==[YAML loader: voltage_source round-trip]==] [==[YAML loader: pwm_voltage_source round-trip]==] [==[YAML loader: sine_voltage_source round-trip]==] [==[YAML loader: mosfet_level1 round-trip]==] [==[YAML loader: pulse_voltage_source round-trip]==] [==[YAML loader: current_source round-trip]==] [==[YAML loader: resistor round-trip (R in ohms → G = 1/R)]==] [==[YAML loader: capacitor round-trip]==] [==[YAML loader: inductor round-trip]==] [==[YAML loader: diode round-trip]==] [==[YAML loader: nonlinear_diode round-trip]==] [==[YAML loader: mosfet round-trip]==] [==[YAML loader: mosfet_with_body_diode adds 2 branches]==] [==[YAML loader: igbt round-trip]==] [==[YAML loader: transformer round-trip]==] [==[YAML loader: simulation: block populates SimulationOptions]==] [==[YAML loader: missing R on resistor throws with name]==] [==[YAML loader: unknown device type throws with the type name]==] [==[YAML loader: missing top-level circuit: throws]==] [==[YAML-built half-wave rectifier matches direct builder]==] [==[YAML-built V_dc + R: DC solve gives v_node = V_dc]==] [==[YAML loader: malformed YAML throws cleanly]==] [==[YAML loader: simulation.store_every is honoured, not ignored]==])
